//! Rendered-artifact cache key cross-target parity (plan 031 D5): the Rust
//! a2r emission of artifact_hash.at must produce the SAME keys as the TS
//! emission (packages/engine/src/render/artifact-hash.generated.ts + the
//! artifact-key.ts charCodeAt wrapper). The golden text is regenerated by
//! the TS side — packages/engine/src/render/__tests__/artifact-hash.test.ts
//! (runs on every engine `pnpm test`) — and asserted here. A mismatch
//! means the two emissions of the same .at source (or the two UTF-16 unit
//! materializers) have drifted.
//!
//! Golden format: `<corpus index> <kind>:<utf16 len>:<8-hex FNV-1a>`.

use autodown_core::artifact_hash::artifact_hash;

/// Same probe corpus as the TS generator — kept in lockstep by the golden
/// itself (adding an entry there without regenerating fails here, and vice
/// versa). CJK / astral emoji / multiline / empty / backslash-heavy.
const CORPUS: &[(&str, &str)] = &[
    ("MathBlock", "e = mc^2"),
    ("MathBlock", "\\frac{1}{2} + \\sqrt{x}"),
    ("MathBlock", ""),
    ("Mermaid", "graph TD; A-->B;"),
    ("Mermaid", "graph LR;\n A[开始] --> B[结束];\n B --> C{判定?};\n"),
    // astral emoji = surrogate pairs (UTF-16 len 2 per emoji, 1 scalar —
    // the sharpest divergence probe)
    ("Mermaid", "flowchart TD\nA[😀] --> B[🎉]\n"),
    (
        "Mermaid",
        "sequenceDiagram\nparticipant 中方\n中方->>美方: 你好 world 🌏\n",
    ),
    ("MathBlock", "\\sum_{i=1}^{n} a_i ≠ 0 ⇒ ∀ε>0"),
    // same source under the other kind — kind mixing probe
    ("MathBlock", "graph TD; A-->B;"),
    ("Mermaid", "graph TD;\n A[\"quoted \\\"label\\\"\"]-->B;\n"),
];

fn projection() -> Vec<String> {
    CORPUS
        .iter()
        .enumerate()
        .map(|(i, (kind, source))| format!("{} {}", i, artifact_hash(kind, source)))
        .collect()
}

#[test]
fn matches_the_ts_generated_golden() {
    let golden = include_str!("golden/artifact-hash.golden.txt");
    let expected: Vec<&str> = golden
        .lines()
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .collect();
    let actual = projection();
    assert_eq!(
        expected.len(),
        actual.len(),
        "corpus size drifted vs the TS generator ({} golden lines, {} rust probes)",
        expected.len(),
        actual.len()
    );
    for (exp, act) in expected.iter().zip(actual.iter()) {
        assert_eq!(exp, act, "artifact hash key drifted from the TS emission");
    }
}

#[test]
fn key_shape_is_kind_len_hex() {
    let key = artifact_hash("MathBlock", "e = mc^2");
    let parts: Vec<&str> = key.split(':').collect();
    assert_eq!(parts.len(), 3);
    assert_eq!(parts[0], "MathBlock");
    assert_eq!(parts[1], "8");
    assert_eq!(parts[2].len(), 8);
    assert!(
        parts[2].chars().all(|c| c.is_ascii_hexdigit() && !c.is_ascii_uppercase()),
        "hex must be lowercase: {}",
        parts[2]
    );
}
