//! Cross-target parity test (plan 016 Phase 4): the Rust a2r emission of
//! block_model.at + serializer.at must produce byte-identical `.ad` output to
//! the TS emission for the same hand-constructed trees. The golden sections
//! are generated by the TS side — see
//! packages/core/src/__tests__/rust-parity-gen.test.ts (runs in `pnpm test`,
//! rewrites tests/golden/parity.ad). A mismatch here means the two emissions
//! of the same .at sources have drifted.

use autodown_core::block_model::{
    attrSet, block, leafBlock, markedSpan, rng, span, Attr, BlockNode, BlockType, InlineSpan,
    Mark, Value,
};
use autodown_core::serializer::serialize;

fn doc(children: Vec<BlockNode>) -> BlockNode {
    BlockNode {
        id: "doc".to_string(),
        kind: BlockType::Paragraph,
        attrs: vec![],
        children,
        inlines: vec![],
        source: rng(0, 0),
    }
}

fn para(id: &str, text: &str) -> BlockNode {
    leafBlock(id, BlockType::Paragraph, text)
}

fn case_heading_paragraph_list() -> String {
    let mut h = block("block-0", BlockType::Heading);
    h.attrs = attrSet(h.attrs, "level", Value::Int(1));
    h.inlines = vec![span("Hello")];

    let p = BlockNode {
        id: "block-1".to_string(),
        kind: BlockType::Paragraph,
        attrs: vec![],
        children: vec![],
        inlines: vec![
            span("a "),
            markedSpan("bold", vec![Mark::Strong]),
            span(" move"),
        ],
        source: rng(0, 0),
    };

    let item = |id: &str, text: &str| BlockNode {
        id: id.to_string(),
        kind: BlockType::ListItem,
        attrs: vec![],
        children: vec![para(&format!("{}-0", id), text)],
        inlines: vec![],
        source: rng(0, 0),
    };
    let mut list = block("block-2", BlockType::ListBlock);
    list.attrs = attrSet(list.attrs, "ordered", Value::Bool(false));
    list.children = vec![item("block-2-0", "one"), item("block-2-1", "two")];

    serialize(doc(vec![h, p, list]), false)
}

fn case_table_with_ial() -> String {
    let cell = |id: &str, header: bool, text: &str| BlockNode {
        id: id.to_string(),
        kind: BlockType::TableCell,
        attrs: attrSet(
            attrSet(vec![], "header", Value::Bool(header)),
            "align",
            Value::Str("".to_string()),
        ),
        children: vec![],
        inlines: vec![span(text)],
        source: rng(0, 0),
    };
    let row = |id: &str, header: bool, text: &str| BlockNode {
        id: id.to_string(),
        kind: BlockType::TableRow,
        attrs: vec![],
        children: vec![cell(&format!("{}-c0", id), header, text)],
        inlines: vec![],
        source: rng(0, 0),
    };
    let ial = Value::AttrsV(vec![
        Attr {
            key: "cols".to_string(),
            value: Value::ListV(vec![Value::Int(120), Value::Null]),
        },
        Attr {
            key: "rows".to_string(),
            value: Value::ListV(vec![Value::Int(40)]),
        },
    ]);
    let mut table = block("block-0", BlockType::Table);
    table.children = vec![row("block-0-h", true, "a"), row("block-0-r0", false, "1")];
    table.attrs = attrSet(table.attrs, "ial", ial);

    serialize(doc(vec![table]), false)
}

fn case_emit_ids() -> String {
    // New anchor semantics: only the  attr (lifted ^token) re-emits
    // under emitIds=true; fallback ids stay internal.
    let mut h = block("title-1", BlockType::Heading);
    h.attrs = attrSet(h.attrs, "level", Value::Int(2));
    h.attrs = attrSet(h.attrs, "anchor", Value::Str("title-1".to_string()));
    h.inlines = vec![span("Title")];
    let anchored = para("my-anchor", "kept ^my-anchor");
    serialize(doc(vec![h, anchored]), true)
}

fn case_hardbreak_and_fence() -> String {
    let hb = BlockNode {
        id: "block-0".to_string(),
        kind: BlockType::Paragraph,
        attrs: vec![],
        children: vec![],
        inlines: vec![
            span("line one"),
            InlineSpan {
                text: "\n".to_string(),
                marks: vec![],
                attrs: vec![],
            },
            span("line two"),
        ],
        source: rng(0, 0),
    };
    let mut f = block("block-1", BlockType::Fence);
    f.attrs = attrSet(f.attrs, "language", Value::Str("ts".to_string()));
    f.inlines = vec![span("const x = 1\n")];
    serialize(doc(vec![hb, f]), false)
}

/// Split the golden file into (name, output) sections. Each section is a
/// `=== name ===` header line followed by the serializer output (which always
/// ends with a trailing newline).
fn golden_sections() -> Vec<(String, String)> {
    let golden = include_str!("golden/parity.ad");
    let mut sections: Vec<(String, String)> = Vec::new();
    let mut cur_name: Option<String> = None;
    let mut cur_body = String::new();
    for line in golden.lines() {
        if let Some(name) = line.strip_prefix("=== ").and_then(|l| l.strip_suffix(" ===")) {
            if let Some(prev) = cur_name.take() {
                sections.push((prev, std::mem::take(&mut cur_body)));
            }
            cur_name = Some(name.to_string());
        } else {
            cur_body.push_str(line);
            cur_body.push('\n');
        }
    }
    if let Some(prev) = cur_name.take() {
        sections.push((prev, cur_body));
    }
    sections
}

#[test]
fn parity_with_ts_emission() {
    let built: Vec<(&str, String)> = vec![
        ("heading_paragraph_list", case_heading_paragraph_list()),
        ("table_with_ial", case_table_with_ial()),
        ("emit_ids", case_emit_ids()),
        ("hardbreak_and_fence", case_hardbreak_and_fence()),
    ];
    let golden = golden_sections();
    assert_eq!(
        golden.len(),
        built.len(),
        "golden section count drifted from the Rust cases"
    );
    for ((gname, gout), (bname, bout)) in golden.iter().zip(built.iter()) {
        assert_eq!(gname, bname, "section order drifted");
        assert_eq!(
            gout, bout,
            "parity mismatch in case `{gname}`: rust emission differs from TS golden"
        );
    }
}
