import { expect, test } from '@playwright/test'
import { openApp, treeNode } from './helpers'
import { WORKSPACE_ROOT } from './runtime'

test.describe('workspace + file tree', () => {
  test('workspace auto-loads and file tree renders fixture files', async ({ page }) => {
    await openApp(page)

    // Expected files from the fixture workspace (tmp/wiki-demo/wiki +
    // the E2E-only page generated by scripts/e2e-prepare.mjs).
    for (const name of ['index.ad', 'Tasks.ad', 'Projects.ad', 'Hello World.ad', 'CAP 定理.ad', 'E2E Links.ad', 'journals']) {
      await expect(treeNode(page, name)).toBeVisible()
    }

    // Empty main area hints the user to pick a file.
    await expect(page.getByText('Select a file from the sidebar to open it.')).toBeVisible()
  })

  test('WorkspaceOpener UI opens a workspace by path', async ({ page }) => {
    // Force the backend to report "no workspace" so the opener UI appears.
    // The POST /api/workspace/open call is NOT intercepted and goes to the
    // real backend (which is idempotent — it already has the fixture open).
    await page.route('**/api/workspace', (route) => {
      if (route.request().method() === 'GET') {
        return route.fulfill({ json: { root: null, wiki_dir: null } })
      }
      return route.continue()
    })

    await page.goto('/')
    await expect(page.getByRole('heading', { name: 'Jade Garden' })).toBeVisible()

    await page.locator('input[placeholder*="粘贴完整目录路径"]').fill(WORKSPACE_ROOT)
    await page.getByRole('button', { name: 'Open', exact: true }).click()

    // After open, the opener is replaced by the main area and the tree loads.
    await expect(treeNode(page, 'index.ad')).toBeVisible()
    await expect(treeNode(page, 'Tasks.ad')).toBeVisible()
  })
})
