import { expect, test } from '@playwright/test'
import { openApp, openFile, visibleEditor } from './helpers'

test.describe('wiki links', () => {
  test('clicking a [[wiki link]] in the editor opens that file tab', async ({ page }) => {
    await openApp(page)
    await openFile(page, 'index.ad', '欢迎来到 Jade Garden')

    await visibleEditor(page)
      .locator('.autodown-wikilink-label', { hasText: 'Hello World' })
      .first()
      .click()

    // A new tab opens with the linked page loaded.
    await expect(visibleEditor(page)).toContainText('这是一段示例文本')
    await expect(page.locator('button', { hasText: 'Hello World' }).first()).toBeVisible()
  })

  test('clicking a dangling [[wiki link]] offers to create the page', async ({ page }) => {
    // E2E Links.ad (generated by scripts/e2e-prepare.mjs) contains a dangling
    // [[E2E Dangling Page]] link mid-document.
    page.on('dialog', (dialog) => void dialog.accept())

    await openApp(page)
    await openFile(page, 'E2E Links.ad', '悬空链接')

    // NOTE: dispatchEvent, not click — the editor's block insert-handle
    // (.autodown-block-boundary::after, a 28px pointer-events:auto strip at
    // every block boundary) overlays links on the last line of a block and
    // intercepts pointer events. This pins the open-wiki-link flow itself.
    await visibleEditor(page)
      .locator('.autodown-wikilink-label', { hasText: 'E2E Dangling Page' })
      .first()
      .dispatchEvent('click')

    // Confirm dialog accepted → page created → new tab opens.
    await expect(page.locator('button', { hasText: 'E2E Dangling Page' }).first()).toBeVisible()
  })
})
