#![allow(non_snake_case)]
#![allow(dead_code)]

// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct AgTaskRef {
    pub scheduled: String,
    pub deadline: String,
    pub index: i64,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct AgGroup {
    pub date: String,
    pub indexes: Vec<i64>,
}

fn isWs(c: i64) -> bool {
    if c == 32 {
        return true;
    }
    if c == 9 {
        return true;
    }
    if c == 10 {
        return true;
    }
    if c == 13 {
        return true;
    }
    if c == 11 {
        return true;
    }
    if c == 12 {
        return true;
    }
    return false;
}

fn isDigit(c: i64) -> bool {
    return c >= 48 && c <= 57;
}

fn digitChar(d: i64) -> String {
    return "0123456789".chars().take((d + 1) as usize).skip((d) as usize).collect::<String>().to_string();
}

fn div10(v: i64) -> i64 {
    let mut q: i64 = 0;
    let mut r: i64 = v;
    while r >= 10 {
        r = r - 10;
        q = q + 1;
    }
    return q;
}

fn div100(v: i64) -> i64 {
    let mut q: i64 = 0;
    let mut r: i64 = v;
    while r >= 100 {
        r = r - 100;
        q = q + 1;
    }
    return q;
}

fn pad2(v: i64) -> String {
    if v < 10 {
        return format!("{}{}", "0", digitChar(v));
    }
    let tens = div10(v);
    let ones: i64 = v - tens * 10;
    return format!("{}{}", digitChar(tens), digitChar(ones));
}

fn pad4(v: i64) -> String {
    let hi = div100(v);
    let lo: i64 = v - hi * 100;
    return format!("{}{}", pad2(hi), pad2(lo));
}

fn daysInMonth(year: i64, month: i64) -> i64 {

    let lengths: Vec<i64> = vec![31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
    if month < 1 {
        return 0;
    }
    if month > 12 {
        return 0;
    }
    if month != 2 {
        return lengths[(month - 1) as usize].clone();
    }
    let mut leap: bool = false;
    if year % 4 == 0 {
        leap = true;
        if year % 100 == 0 {
            leap = false;
            if year % 400 == 0 {
                leap = true;
            }        }    }
    if leap {
        return 29;
    }
    return 28;
}

pub fn normalizeDate(raw: &str) -> String {
    let n: i64 = (raw.chars().count() as i64);
    let mut s: i64 = 0;
    while s < n {
        if !(isWs(raw.chars().nth((s) as usize).unwrap_or('\0') as i64)) {
            break;
        }
        s += 1;
    }
    let mut e: i64 = s;
    while e < n {
        if isWs(raw.chars().nth((e) as usize).unwrap_or('\0') as i64) {
            break;
        }
        e += 1;
    }
    if e <= s {
        return "".to_string();
    }

    let mut i: i64 = s;
    let mut year: i64 = 0;
    let mut k: i64 = 0;
    while k < 4 {
        if !(isDigit(raw.chars().nth((i) as usize).unwrap_or('\0') as i64)) {
            return "".to_string();
        }
        year = year * 10 + raw.chars().nth((i) as usize).unwrap_or('\0') as i64 - 48;
        i += 1;
        k += 1;
    }
    if raw.chars().nth((i) as usize).unwrap_or('\0') as i64 != 45 {
        return "".to_string();
    }
    i += 1;

    let mut month: i64 = 0;
    let mut mdigits: i64 = 0;
    while i < e {
        if !(isDigit(raw.chars().nth((i) as usize).unwrap_or('\0') as i64)) {
            break;
        }
        if mdigits >= 2 {
            break;
        }
        month = month * 10 + raw.chars().nth((i) as usize).unwrap_or('\0') as i64 - 48;
        i += 1;
        mdigits += 1;
    }
    if mdigits == 0 {
        return "".to_string();
    }
    if i >= e {
        return "".to_string();
    }
    if raw.chars().nth((i) as usize).unwrap_or('\0') as i64 != 45 {
        return "".to_string();
    }
    i += 1;

    let mut day: i64 = 0;
    let mut ddigits: i64 = 0;
    while i < e {
        if !(isDigit(raw.chars().nth((i) as usize).unwrap_or('\0') as i64)) {
            break;
        }
        if ddigits >= 2 {
            break;
        }
        day = day * 10 + raw.chars().nth((i) as usize).unwrap_or('\0') as i64 - 48;
        i += 1;
        ddigits += 1;
    }
    if ddigits == 0 {
        return "".to_string();
    }
    if i != e {
        return "".to_string();
    }
    if day < 1 {
        return "".to_string();
    }
    if day > daysInMonth(year, month) {
        return "".to_string();
    }
    return format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", pad4(year), "-"), pad2(month)), "-"), pad2(day));
}

fn strGE(a: &str, b: &str) -> bool {
    return a >= b;
}

fn strLE(a: &str, b: &str) -> bool {
    return a <= b;
}

pub fn groupAgenda(mut entries: Vec<AgTaskRef>, today: &str, end: &str) -> Vec<AgGroup> {

    let mut pairDate: Vec<String> = vec![];
    let mut pairIdx: Vec<i64> = vec![];
    let count: i64 = (entries.len() as i64);
    let mut i: i64 = 0;
    while i < count {
        let en = entries[(i) as usize].clone();
        let ds = normalizeDate(en.scheduled.as_str());
        if ds != "" && strGE(ds.as_str(), today) && strLE(ds.as_str(), end) {
            pairDate.push(ds.to_string());
            pairIdx.push(en.index);
        }
        let dd = normalizeDate(en.deadline.as_str());
        if dd != "" && strGE(dd.as_str(), today) && strLE(dd.as_str(), end) {
            pairDate.push(dd.to_string());
            pairIdx.push(en.index);
        }
        i += 1;
    }

    let mut unique: Vec<String> = vec![];
    let mut j: i64 = 0;
    while j < (pairDate.len() as i64) {
        let d = pairDate[(j) as usize].clone();
        let mut seen: bool = false;
        let mut q: i64 = 0;
        while q < (unique.len() as i64) {
            if unique[(q) as usize].clone() == d {
                seen = true;
            }
            q += 1;
        }
        if !(seen) {
            unique.push(d.to_string());
        }
        j += 1;
    }


    let mut dates: Vec<String> = vec![];
    let mut last: String = "".to_string();
    while (dates.len() as i64) < (unique.len() as i64) {
        let mut best: String = "".to_string();
        let mut r: i64 = 0;
        while r < (unique.len() as i64) {
            let u = unique[(r) as usize].clone();
            if last == "" || u > last {
                if best == "" || u < best {
                    best = u.to_string();
                }            }
            r += 1;
        }
        dates.push(best.to_string());
        last = best.to_string();
    }

    let mut out: Vec<AgGroup> = vec![];
    let mut di: i64 = 0;
    while di < (dates.len() as i64) {
        let d = dates[(di) as usize].clone();
        let mut idxs: Vec<i64> = vec![];
        let mut p: i64 = 0;
        while p < (pairDate.len() as i64) {
            if pairDate[(p) as usize].clone() == d {
                idxs.push(pairIdx[(p) as usize].clone());
            }
            p += 1;
        }
        out.push(AgGroup { date: d.to_string(), indexes: idxs });
        di += 1;
    }
    return out;
}
