#![allow(non_snake_case)]
#![allow(dead_code)]

// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct PBlock {
    pub kind: String,
    pub content: String,
    pub blockId: String,
    pub lineStart: i64,
    pub lineEnd: i64,
}

pub fn startsWithStr(s: &str, prefix: &str) -> bool {
    if (s.chars().count() as i64) < (prefix.chars().count() as i64) {
        return false;
    }
    return s.chars().take(((prefix.chars().count() as i64)) as usize).skip((0) as usize).collect::<String>() == prefix;
}

pub fn endsWithStr(s: &str, suffix: &str) -> bool {
    if (s.chars().count() as i64) < (suffix.chars().count() as i64) {
        return false;
    }
    return s.chars().take(((s.chars().count() as i64)) as usize).skip(((s.chars().count() as i64) - (suffix.chars().count() as i64)) as usize).collect::<String>() == suffix;
}

fn isWhitespaceCode(c: i64) -> bool {
    if c == 32 {
        return true;
    }
    if c == 9 {
        return true;
    }
    if c == 10 {
        return true;
    }
    if c == 13 {
        return true;
    }
    if c == 11 {
        return true;
    }
    if c == 12 {
        return true;
    }
    return false;
}

pub fn trimStartStr(s: &str) -> String {
    let mut p: i64 = 0;
    while p < (s.chars().count() as i64) {
        if !(isWhitespaceCode(s.chars().nth((p) as usize).unwrap_or('\0') as i64)) {
            break;
        }
        p += 1;
    }
    if p == 0 {
        return s.to_string();
    }
    return s.chars().skip((p) as usize).collect::<String>().to_string();
}

pub fn trimEndStr(s: &str) -> String {
    let mut end: i64 = (s.chars().count() as i64);
    while end > 0 {
        if !(isWhitespaceCode(s.chars().nth((end - 1) as usize).unwrap_or('\0') as i64)) {
            break;
        }
        end -= 1;
    }
    if end == (s.chars().count() as i64) {
        return s.to_string();
    }
    return s.chars().take((end) as usize).skip((0) as usize).collect::<String>().to_string();
}

pub fn trimStr(s: &str) -> String {
    return trimStartStr(trimEndStr(s).as_str());
}

pub fn findStr(s: &str, needle: &str) -> i64 {
    let nLen: i64 = (needle.chars().count() as i64);
    let sLen: i64 = (s.chars().count() as i64);
    if nLen == 0 {
        return 0;
    }
    if sLen < nLen {
        return -1;
    }
    let mut i: i64 = 0;
    while i + nLen <= sLen {
        if s.chars().take((i + nLen) as usize).skip((i) as usize).collect::<String>() == needle {
            return i;
        }
        i += 1;
    }
    return -1;
}

fn joinLines(lines: Vec<String>, start: i64, end: i64) -> String {
    let mut out: String = "".to_string();
    let mut i: i64 = start;
    while i < end {
        if i > start {
            out = format!("{}{}", out, "\n");
        }
        out = format!("{}{}", out, lines[(i) as usize].clone());
        i += 1;
    }
    return out;
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct AnchorSplit {
    pub content: String,
    pub id: String,
}

fn isAnchorIdChar(c: i64) -> bool {
    if c >= 48 && c <= 57 {
        return true;
    }
    if c >= 65 && c <= 90 {
        return true;
    }
    if c >= 97 && c <= 122 {
        return true;
    }
    if c == 45 {
        return true;
    }
    if c == 95 {
        return true;
    }
    return false;
}

fn isAnchorId(id: &str) -> bool {
    let n: i64 = (id.chars().count() as i64);
    if n == 0 {
        return false;
    }
    let mut i: i64 = 0;
    while i < n {
        if !(isAnchorIdChar(id.chars().nth((i) as usize).unwrap_or('\0') as i64)) {
            return false;
        }
        i += 1;
    }
    return true;
}

pub fn extractAnchor(content: &str) -> AnchorSplit {
    let t = trimEndStr(content);
    let n: i64 = (t.chars().count() as i64);
    let mut s: i64 = n;
    while s > 0 {
        let c = t.chars().nth((s - 1) as usize).unwrap_or('\0') as i64;
        if c == 32 || c == 9 {
            break;
        }
        s -= 1;
    }
    if s <= 0 {
        return AnchorSplit { content: t.to_string(), id: "".to_string() };
    }
    if t.chars().nth((s) as usize).unwrap_or('\0') as i64 != 94 {
        return AnchorSplit { content: t.to_string(), id: "".to_string() };
    }
    let id = t.chars().take((n) as usize).skip((s + 1) as usize).collect::<String>();
    if !(isAnchorId(id.as_str())) {
        return AnchorSplit { content: t.to_string(), id: "".to_string() };
    }
    let stripped = trimEndStr(t.chars().take((s - 1) as usize).skip((0) as usize).collect::<String>().as_str());
    return AnchorSplit { content: stripped.to_string(), id: id.to_string() };
}

/// Mirror of parser.rs extract_anchor: trailing "\s+^token" (whitespace-run
/// before ^ required) becomes the block id; the remainder is the content.
fn isHrLine(line: &str) -> bool {
    let t = trimStr(line);
    if t == "---" {
        return true;
    }
    if t == "***" {
        return true;
    }
    if t == "___" {
        return true;
    }
    return false;
}

fn headingLevelOf(trimmed: &str) -> i64 {
    let mut level: i64 = 0;
    while level < (trimmed.chars().count() as i64) {
        if trimmed.chars().nth((level) as usize).unwrap_or('\0') as i64 == 35 {
            level += 1;
        } else {
            break;
        }

    }
    if level == 0 {
        return 0;
    }
    if level > 6 {
        return 0;
    }
    if level == (trimmed.chars().count() as i64) {
        return 0;
    }
    if trimmed.chars().nth((level) as usize).unwrap_or('\0') as i64 != 32 {
        return 0;
    }
    return level;
}

fn orderedPrefixLen(trimmed: &str) -> i64 {





    let mut d: i64 = 0;
    while d < (trimmed.chars().count() as i64) {
        let c = trimmed.chars().nth((d) as usize).unwrap_or('\0') as i64;
        if c >= 48 && c <= 57 {
            d += 1;
        } else {
            break;
        }

    }
    if d == 0 {
        return -1;
    }
    if startsWithStr(trimmed.chars().skip((d) as usize).collect::<String>().as_str(), ". ") {
        return d + 2;
    }
    return -1;
}

pub fn parseHeadingLine(line: &str, idx: i64) -> PBlock {
    let trimmed = trimStartStr(line);
    let level = headingLevelOf(trimmed.as_str());
    let content = trimStr(trimmed.chars().skip((level + 1) as usize).collect::<String>().as_str());
    let split = extractAnchor(content.as_str());
    return PBlock { kind: "heading".to_string(), content: split.content.to_string(), blockId: split.id.to_string(), lineStart: idx, lineEnd: idx + 1 };
}

pub fn parseListItemLine(line: &str, idx: i64) -> PBlock {
    let trimmed = trimStartStr(line);
    let mut kind: String = "".to_string();
    let mut prefixLen: i64 = 0;
    if startsWithStr(trimmed.as_str(), "- [ ] ") || startsWithStr(trimmed.as_str(), "- [x] ") || startsWithStr(trimmed.as_str(), "- [X] ") {
        kind = "task".to_string();
        prefixLen = 6;
    } else {
        if startsWithStr(trimmed.as_str(), "- ") {
            kind = "bullet".to_string();
            prefixLen = 2;
        } else {
            let oLen = orderedPrefixLen(trimmed.as_str());
            if oLen > 0 {
                kind = "ordered".to_string();
                prefixLen = findStr(trimmed.as_str(), ". ") + 2;
            }        }
    }

    let content = trimStr(trimmed.chars().skip((prefixLen) as usize).collect::<String>().as_str());
    let split = extractAnchor(content.as_str());
    return PBlock { kind: kind.to_string(), content: split.content.to_string(), blockId: split.id.to_string(), lineStart: idx, lineEnd: idx + 1 };
}

pub fn isBlockStartLine(line: &str) -> bool {
    let t = trimStartStr(line);
    if startsWithStr(t.as_str(), "#") {
        return true;
    }
    if startsWithStr(t.as_str(), "- ") {
        return true;
    }
    if startsWithStr(t.as_str(), "- [") {
        return true;
    }
    if startsWithStr(t.as_str(), ">") {
        return true;
    }
    if startsWithStr(t.as_str(), "```") {
        return true;
    }
    if startsWithStr(t.as_str(), ":::") {
        return true;
    }
    if startsWithStr(t.as_str(), "---") {
        return true;
    }
    if startsWithStr(t.as_str(), "***") {
        return true;
    }
    if startsWithStr(t.as_str(), "___") {
        return true;
    }
    return orderedPrefixLen(t.as_str()) > 0;
}

pub fn parseBody(body: &str) -> Vec<PBlock> {
    let lines = body.split("\n").map(|s| s.to_string()).collect::<Vec<String>>();
    let mut blocks: Vec<PBlock> = vec![];
    let mut i: i64 = 0;


    let mut count: i64 = (lines.len() as i64);
    if count > 0 {
        if lines[(count - 1) as usize].clone() == "" {
            count -= 1;
        }    }
    while i < count {
        let line = lines[(i) as usize].clone();
        if startsWithStr(line.as_str(), "```") {
            let end = scanFenceEnd(lines.clone(), count, i, "```");
            blocks.push(PBlock { kind: "code".to_string(), content: joinLines(lines.clone(), i, end).to_string(), blockId: "".to_string(), lineStart: i, lineEnd: end });
            i = end;
        } else {
            if startsWithStr(line.as_str(), ":::") {
                let mut kind: String = "callout".to_string();
                if startsWithStr(line.as_str(), ":::details") || startsWithStr(line.as_str(), "::: details") {
                    kind = "details".to_string();
                }                let end2 = scanFenceEnd(lines.clone(), count, i, ":::");
                blocks.push(PBlock { kind: kind.to_string(), content: joinLines(lines.clone(), i, end2).to_string(), blockId: "".to_string(), lineStart: i, lineEnd: end2 });
                i = end2;
            } else {
                if isHrLine(line.as_str()) {
                    blocks.push(PBlock { kind: "hr".to_string(), content: line.to_string(), blockId: "".to_string(), lineStart: i, lineEnd: i + 1 });
                    i += 1;
                } else {
                    if headingLevelOf(trimStartStr(line.as_str()).as_str()) > 0 {
                        blocks.push(parseHeadingLine(line.as_str(), i));
                        i += 1;
                    } else {
                        if isListItemLine(line.as_str()) {
                            blocks.push(parseListItemLine(line.as_str(), i));
                            i += 1;
                        } else {
                            if startsWithStr(line.as_str(), ">") {
                                let end3 = scanQuoteEnd(lines.clone(), count, i);
                                blocks.push(PBlock { kind: "blockquote".to_string(), content: quoteContent(lines.clone(), i, end3).to_string(), blockId: "".to_string(), lineStart: i, lineEnd: end3 });
                                i = end3;
                            } else {
                                if trimStr(line.as_str()) == "" {
                                    i += 1;
                                } else {
                                    let end4 = scanParagraphEnd(lines.clone(), count, i);
                                    let split = extractAnchor(joinLines(lines.clone(), i, end4).as_str());
                                    blocks.push(PBlock { kind: "paragraph".to_string(), content: split.content.to_string(), blockId: split.id.to_string(), lineStart: i, lineEnd: end4 });
                                    i = end4;
                                }
                            }
                        }
                    }
                }
            }
        }

    }
    return blocks;
}

fn isListItemLine(line: &str) -> bool {
    let t = trimStartStr(line);
    if startsWithStr(t.as_str(), "- [ ] ") {
        return true;
    }
    if startsWithStr(t.as_str(), "- [x] ") {
        return true;
    }
    if startsWithStr(t.as_str(), "- [X] ") {
        return true;
    }
    if startsWithStr(t.as_str(), "- ") {
        return true;
    }
    if orderedPrefixLen(t.as_str()) > 0 {
        return true;
    }
    return false;
}

fn scanFenceEnd(lines: Vec<String>, count: i64, start: i64, fence: &str) -> i64 {
    let mut end: i64 = start + 1;
    while end < count {
        if startsWithStr(trimStartStr(lines[(end) as usize].as_str()).as_str(), fence) {
            end += 1;
            return end;
        }
        end += 1;
    }
    return end;
}

fn scanQuoteEnd(lines: Vec<String>, count: i64, start: i64) -> i64 {
    let mut end: i64 = start;
    while end < count {
        if startsWithStr(lines[(end) as usize].as_str(), ">") {
            end += 1;
        } else {
            break;
        }

    }
    return end;
}

fn quoteContent(lines: Vec<String>, start: i64, end: i64) -> String {
    let mut out: String = "".to_string();
    let mut i: i64 = start;
    while i < end {
        if i > start {
            out = format!("{}{}", out, "\n");
        }
        if startsWithStr(lines[(i) as usize].as_str(), "> ") {
            out = format!("{}{}", out, lines[(i) as usize].clone()[2..].to_string());
        } else {
            out = format!("{}{}", out, lines[(i) as usize].clone()[1..].to_string());
        }

        i += 1;
    }
    return out;
}

fn scanParagraphEnd(lines: Vec<String>, count: i64, start: i64) -> i64 {
    let mut end: i64 = start;
    while end < count {
        if trimStr(lines[(end) as usize].as_str()) == "" {
            break;
        }
        if isBlockStartLine(lines[(end) as usize].as_str()) {
            break;
        }
        end += 1;
    }
    return end;
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct FrontSplit {
    pub yaml: String,
    pub body: String,
    pub hasMarker: bool,
}

pub fn splitFrontmatterScan(text: &str) -> FrontSplit {
    let trimmed = trimStartStr(text);
    if !(startsWithStr(trimmed.as_str(), "---")) {
        return FrontSplit { yaml: "".to_string(), body: text.to_string(), hasMarker: false };
    }
    let rest = trimmed.chars().skip((3) as usize).collect::<String>();
    let end = findStr(rest.as_str(), "\n---");
    if end < 0 {
        return FrontSplit { yaml: "".to_string(), body: text.to_string(), hasMarker: false };
    }
    return FrontSplit { yaml: rest.chars().take((end) as usize).skip((0) as usize).collect::<String>().to_string(), body: trimStartStr(rest.chars().skip((end + 4) as usize).collect::<String>().as_str()).to_string(), hasMarker: true };
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct PropPair {
    pub key: String,
    pub value: String,
}

pub fn findIdPropertyLine(line: &str) -> String {
    let t = trimStartStr(line);
    if !(startsWithStr(t.as_str(), "id::")) {
        return "".to_string();
    }
    let v = trimEndStr(trimStartStr(t.chars().skip((4) as usize).collect::<String>().as_str()).as_str());
    if !(isUuid36(v.as_str())) {
        return "".to_string();
    }
    return v;
}

/// Mirror of ID_PROPERTY_RE: `id:: <uuid v4 shape>` after leading whitespace.
fn isHexChar(c: i64) -> bool {
    if c >= 48 && c <= 57 {
        return true;
    }
    if c >= 65 && c <= 70 {
        return true;
    }
    if c >= 97 && c <= 102 {
        return true;
    }
    return false;
}

fn isUuid36(s: &str) -> bool {
    if (s.chars().count() as i64) != 36 {
        return false;
    }
    let mut i: i64 = 0;
    while i < 36 {
        let c = s.chars().nth((i) as usize).unwrap_or('\0') as i64;
        if i == 8 || i == 13 || i == 18 || i == 23 {
            if c != 45 {
                return false;
            }        } else {
            if !(isHexChar(c)) {
                return false;
            }        }

        i += 1;
    }
    return true;
}

fn isKeyStartChar(c: i64) -> bool {
    if c >= 65 && c <= 90 {
        return true;
    }
    if c >= 97 && c <= 122 {
        return true;
    }
    if c == 95 {
        return true;
    }
    return false;
}

fn isKeyChar(c: i64) -> bool {
    if isKeyStartChar(c) {
        return true;
    }
    if c >= 48 && c <= 57 {
        return true;
    }
    if c == 45 {
        return true;
    }
    return false;
}

pub fn parsePropertyLine(line: &str) -> PropPair {
    let t = trimStartStr(line);
    let n: i64 = (t.chars().count() as i64);
    if n < 3 {
        return PropPair { key: "".to_string(), value: "".to_string() };
    }
    if !(isKeyStartChar(t.chars().nth((0) as usize).unwrap_or('\0') as i64)) {
        return PropPair { key: "".to_string(), value: "".to_string() };
    }
    let mut e: i64 = 1;
    while e < n {
        let c = t.chars().nth((e) as usize).unwrap_or('\0') as i64;
        if isKeyChar(c) {
            e += 1;
        } else {
            break;
        }

    }
    if !(startsWithStr(t.chars().skip((e) as usize).collect::<String>().as_str(), "::")) {
        return PropPair { key: "".to_string(), value: "".to_string() };
    }
    let key = t.chars().take((e) as usize).skip((0) as usize).collect::<String>();
    let value = trimStartStr(t.chars().skip((e + 2) as usize).collect::<String>().as_str());
    return PropPair { key: key.to_string(), value: value.to_string() };
}

pub fn parseBlockPropertiesLines(mut lines: Vec<String>) -> Vec<PropPair> {
    let mut out: Vec<PropPair> = vec![];
    let mut i: i64 = 0;
    while i < (lines.len() as i64) {
        let pair = parsePropertyLine(lines[(i) as usize].as_str());
        if pair.key != "" {
            out.push(pair.clone());
        }
        i += 1;
    }
    return out;
}
