#![allow(non_snake_case)]
#![allow(dead_code)]

// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct SrPage {
    pub path: String,
    pub title: String,
    pub frontmatter: String,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct SrBlock {
    pub uuid: String,
    pub pagePath: String,
    pub blockId: String,
    pub content: String,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct SrHit {
    pub isPage: bool,
    pub path: String,
    pub title: String,
    pub uuid: String,
    pub blockId: String,
    pub content: String,
    pub snippet: String,
}

fn isWs(c: i64) -> bool {
    if c == 32 {
        return true;
    }
    if c == 9 {
        return true;
    }
    if c == 10 {
        return true;
    }
    if c == 13 {
        return true;
    }
    if c == 11 {
        return true;
    }
    if c == 12 {
        return true;
    }
    return false;
}

fn asciiLower(s: &str) -> String {
    let mut out: String = "".to_string();
    let lower: String = "abcdefghijklmnopqrstuvwxyz".to_string();
    let mut i: i64 = 0;
    while i < (s.chars().count() as i64) {
        let c = s.chars().nth((i) as usize).unwrap_or('\0') as i64;
        if c >= 65 && c <= 90 {
            out = format!("{}{}", out, lower.chars().take((c - 64) as usize).skip((c - 65) as usize).collect::<String>());
        } else {
            out = format!("{}{}", out, s.chars().take((i + 1) as usize).skip((i) as usize).collect::<String>());
        }

        i += 1;
    }
    return out;
}

fn trimWs(s: &str) -> String {
    let mut p: i64 = 0;
    while p < (s.chars().count() as i64) {
        if !(isWs(s.chars().nth((p) as usize).unwrap_or('\0') as i64)) {
            break;
        }
        p += 1;
    }
    let mut end: i64 = (s.chars().count() as i64);
    while end > p {
        if !(isWs(s.chars().nth((end - 1) as usize).unwrap_or('\0') as i64)) {
            break;
        }
        end -= 1;
    }
    return s.chars().take((end) as usize).skip((p) as usize).collect::<String>().to_string();
}

fn findFrom(hay: &str, needle: &str, from: i64) -> i64 {
    let nLen: i64 = (needle.chars().count() as i64);
    let sLen: i64 = (hay.chars().count() as i64);
    if nLen == 0 {
        return -1;
    }
    let mut i: i64 = from;
    while i + nLen <= sLen {
        if hay.chars().take((i + nLen) as usize).skip((i) as usize).collect::<String>() == needle {
            return i;
        }
        i += 1;
    }
    return -1;
}

fn countOccurrences(hay: &str, needle: &str) -> i64 {
    let mut count: i64 = 0;
    let mut pos: i64 = findFrom(hay, needle, 0);
    while pos >= 0 {
        count += 1;
        pos = findFrom(hay, needle, pos + (needle.chars().count() as i64));
    }
    return count;
}

fn buildSnippet(text: &str, needle: &str, openMark: &str, closeMark: &str, ellipsis: &str) -> String {
    let n: i64 = (text.chars().count() as i64);
    let nLen: i64 = (needle.chars().count() as i64);
    let lowerText = asciiLower(text);
    let first: i64 = findFrom(lowerText.as_str(), needle, 0);
    if first < 0 {
        return "".to_string();
    }


    let mut start: i64 = first - 60;
    if start < 0 {
        start = 0;
    }
    if start > 0 {
        while start < first {
            if isWs(text.chars().nth((start) as usize).unwrap_or('\0') as i64) {
                break;
            }
            start += 1;
        }
        while start < first {
            if !(isWs(text.chars().nth((start) as usize).unwrap_or('\0') as i64)) {
                break;
            }
            start += 1;
        }
    }


    let matchEnd: i64 = first + nLen;
    let mut end: i64 = matchEnd + 120;
    if end > n {
        end = n;
    }
    if end < n {
        while end > matchEnd {
            if isWs(text.chars().nth((end) as usize).unwrap_or('\0') as i64) {
                break;
            }
            end -= 1;
        }
        while end > matchEnd {
            if !(isWs(text.chars().nth((end - 1) as usize).unwrap_or('\0') as i64)) {
                break;
            }
            end -= 1;
        }
    }


    let mut out: String = "".to_string();
    if start > 0 {
        out = format!("{}{}", out, ellipsis);
    }
    let mut i: i64 = start;
    while i < end {
        let m: i64 = findFrom(lowerText.as_str(), needle, i);
        if m < 0 {
            break;
        }
        let mEnd: i64 = m + nLen;
        if mEnd > end {
            break;
        }
        out = format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", out, text.chars().take((m) as usize).skip((i) as usize).collect::<String>()), openMark), text.chars().take((mEnd) as usize).skip((m) as usize).collect::<String>()), closeMark);
        i = mEnd;
    }
    out = format!("{}{}", out, text.chars().take((end) as usize).skip((i) as usize).collect::<String>());
    if end < n {
        out = format!("{}{}", out, ellipsis);
    }
    return out;
}

pub fn searchAll(mut pages: Vec<SrPage>, mut blocks: Vec<SrBlock>, rawQuery: &str, limit: i64, openMark: &str, closeMark: &str, ellipsis: &str) -> Vec<SrHit> {
    let mut emptyOut: Vec<SrHit> = vec![];
    let needle = asciiLower(trimWs(rawQuery).as_str());
    if (needle.chars().count() as i64) == 0 {
        return emptyOut;
    }
    if limit <= 0 {
        return emptyOut;
    }

    let mut hits: Vec<SrHit> = vec![];
    let mut counts: Vec<i64> = vec![];

    let mut pi: i64 = 0;
    while pi < (pages.len() as i64) {
        let pg = pages[(pi) as usize].clone();
        let ct = countOccurrences(asciiLower(pg.title.as_str()).as_str(), needle.as_str());
        let cf = countOccurrences(asciiLower(pg.frontmatter.as_str()).as_str(), needle.as_str());
        if ct + cf > 0 {
            let mut snip: String = "".to_string();
            if ct > 0 {
                snip = buildSnippet(pg.title.as_str(), needle.as_str(), openMark, closeMark, ellipsis);
            } else {
                snip = buildSnippet(pg.frontmatter.as_str(), needle.as_str(), openMark, closeMark, ellipsis);
            }
            hits.push(SrHit { isPage: true, path: pg.path.to_string(), title: pg.title.to_string(), uuid: "".to_string(), blockId: "".to_string(), content: "".to_string(), snippet: snip.to_string() });
            counts.push(ct + cf);
        }
        pi += 1;
    }

    let mut bi: i64 = 0;
    while bi < (blocks.len() as i64) {
        let bl = blocks[(bi) as usize].clone();
        let cc = countOccurrences(asciiLower(bl.content.as_str()).as_str(), needle.as_str());
        if cc > 0 {
            let snip = buildSnippet(bl.content.as_str(), needle.as_str(), openMark, closeMark, ellipsis);
            hits.push(SrHit { isPage: false, path: bl.pagePath.to_string(), title: "".to_string(), uuid: bl.uuid.to_string(), blockId: bl.blockId.to_string(), content: bl.content.to_string(), snippet: snip.to_string() });
            counts.push(cc);
        }
        bi += 1;
    }




    let total: i64 = (hits.len() as i64);
    let mut out: Vec<SrHit> = vec![];
    let mut used: Vec<i64> = vec![];
    while (out.len() as i64) < total {
        let mut best: i64 = -1;
        let mut i: i64 = 0;
        while i < total {
            let mut taken: bool = false;
            let mut u: i64 = 0;
            while u < (used.len() as i64) {
                if used[(u) as usize].clone() == i {
                    taken = true;
                }
                u += 1;
            }
            if !(taken) {
                let mut take: bool = false;
                if best == -1 {
                    take = true;
                } else {
                    let mut cand = hits[(i) as usize].clone();
                    let cur = hits[(best) as usize].clone();
                    if cand.isPage != cur.isPage {
                        if cand.isPage {
                            take = true;
                        }                    }                    if cand.isPage == cur.isPage {
                        if counts[(i) as usize].clone() > counts[(best) as usize].clone() {
                            take = true;
                        }                        if counts[(i) as usize].clone() == counts[(best) as usize].clone() {
                            if cand.path < cur.path {
                                take = true;
                            }                            if cand.path == cur.path {
                                if cand.uuid < cur.uuid {
                                    take = true;
                                }                                if cand.uuid == cur.uuid {
                                    if cand.blockId < cur.blockId {
                                        take = true;
                                    }                                }                            }                        }                    }                }
                if take {
                    best = i;
                }            }
            i += 1;
        }
        out.push(hits[(best) as usize].clone());
        used.push(best);
    }


    let mut cut: i64 = limit;
    if cut > total {
        cut = total;
    }
    let mut picked: Vec<SrHit> = vec![];
    let mut k: i64 = 0;
    while k < cut {
        picked.push(out[(k) as usize].clone());
        k += 1;
    }
    return picked;
}
