#![allow(non_snake_case)]
#![allow(dead_code)]

// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct UnlinkedHit {
    pub matched: String,
    pub context: String,
}

fn asciiLower(s: &str) -> String {
    let mut out: String = "".to_string();
    let lower: String = "abcdefghijklmnopqrstuvwxyz".to_string();
    let mut i: i64 = 0;
    while i < (s.chars().count() as i64) {
        let c = s.chars().nth((i) as usize).unwrap_or('\0') as i64;
        if c >= 65 && c <= 90 {
            out = format!("{}{}", out, lower.chars().take((c - 64) as usize).skip((c - 65) as usize).collect::<String>());
        } else {
            out = format!("{}{}", out, s.chars().take((i + 1) as usize).skip((i) as usize).collect::<String>());
        }

        i += 1;
    }
    return out;
}

fn isWordChar(c: i64) -> bool {
    if c >= 97 && c <= 122 {
        return true;
    }
    if c >= 65 && c <= 90 {
        return true;
    }
    if c >= 48 && c <= 57 {
        return true;
    }
    if c == 95 {
        return true;
    }

    if c >= 19968 && c <= 40959 {
        return true;
    }
    return false;
}

fn boundaryOk(text: &str, start: i64, end: i64) -> bool {
    if start > 0 {
        if isWordChar(text.chars().nth((start - 1) as usize).unwrap_or('\0') as i64) {
            return false;
        }    }
    if end < (text.chars().count() as i64) {
        if isWordChar(text.chars().nth((end) as usize).unwrap_or('\0') as i64) {
            return false;
        }    }
    return true;
}

fn lineEndAt(text: &str, pos: i64) -> i64 {
    let mut i: i64 = pos;
    while i < (text.chars().count() as i64) {
        if text.chars().nth((i) as usize).unwrap_or('\0') as i64 == 10 {
            return i;
        }
        i += 1;
    }
    return (text.chars().count() as i64);
}

fn contextAt(text: &str, pos: i64) -> String {
    let mut start: i64 = 0;
    let mut i: i64 = 0;
    while i < pos {
        if text.chars().nth((i) as usize).unwrap_or('\0') as i64 == 10 {
            start = i + 1;
        }
        i += 1;
    }
    let end = lineEndAt(text, pos);

    let mut p: i64 = start;
    let mut e: i64 = end;
    while p < e {
        let c = text.chars().nth((p) as usize).unwrap_or('\0') as i64;
        if c != 32 && c != 9 && c != 10 && c != 13 {
            break;
        }
        p += 1;
    }
    while e > p {
        let c = text.chars().nth((e - 1) as usize).unwrap_or('\0') as i64;
        if c != 32 && c != 9 && c != 10 && c != 13 {
            break;
        }
        e -= 1;
    }
    return text.chars().take((e) as usize).skip((p) as usize).collect::<String>().to_string();
}

fn inWikiSpan(text: &str, start: i64, end: i64) -> bool {
    let mut i: i64 = 0;
    while i < (text.chars().count() as i64) {
        if text.chars().take((i + 2) as usize).skip((i) as usize).collect::<String>() == "[[" {
            let mut j: i64 = i + 2;
            let mut close: i64 = -1;
            while j < (text.chars().count() as i64) {
                if text.chars().nth((j) as usize).unwrap_or('\0') as i64 == 10 {
                    break;
                }
                if text.chars().take((j + 2) as usize).skip((j) as usize).collect::<String>() == "]]" {
                    close = j;
                    break;
                }
                j += 1;
            }
            if close >= 0 {
                if start >= i && end <= close + 2 {
                    return true;
                }                i = close + 2;
            } else {
                i += 2;
            }
        } else {
            i += 1;
        }

    }
    return false;
}

fn scanNames(text: &str, mut names: Vec<String>) -> Vec<UnlinkedHit> {


    let mut out: Vec<UnlinkedHit> = vec![];
    let mut pos: i64 = 0;
    while pos < (text.chars().count() as i64) {
        let mut matchedLen: i64 = 0;
        let mut k: i64 = 0;
        while k < (names.len() as i64) {
            let name = asciiLower(names[(k) as usize].as_str());
            if (name.chars().count() as i64) > 0 && pos + (name.chars().count() as i64) <= (text.chars().count() as i64) {
                let slice = asciiLower(text.chars().take((pos + (name.chars().count() as i64)) as usize).skip((pos) as usize).collect::<String>().as_str());
                if slice == name && boundaryOk(text, pos, pos + (name.chars().count() as i64)) {
                    if !(inWikiSpan(text, pos, pos + (name.chars().count() as i64))) {
                        out.push(UnlinkedHit { matched: text.chars().take((pos + (name.chars().count() as i64)) as usize).skip((pos) as usize).collect::<String>().to_string(), context: contextAt(text, pos).to_string() });
                    }                    matchedLen = (name.chars().count() as i64);
                    break;
                }            }
            k += 1;
        }
        if matchedLen > 0 {
            pos += matchedLen;
        } else {
            pos += 1;
        }

    }
    return out;
}

pub fn findUnlinkedRefs(text: &str, mut names: Vec<String>) -> Vec<UnlinkedHit> {
    let mut out: Vec<UnlinkedHit> = vec![];
    if (names.len() as i64) == 0 {
        return out;
    }
    if (text.chars().count() as i64) == 0 {
        return out;
    }
    let mut scanned: Vec<UnlinkedHit> = scanNames(text, names.clone());
    for h in &scanned {
        out.push(h.clone().clone());
    }
    return out;
}
