//! Palette-map cross-target parity (plan 019 Phase 1 / auto-lang plan-450):
//! the Rust a2r emission of palette_map.at must project identically to the
//! TS emission (packages/engine/src/render/palette-map.generated.ts). The
//! golden text is regenerated by the TS side —
//! packages/engine/src/render/__tests__/rust-palette-parity-gen.test.ts
//! (runs on every engine `pnpm test`) — and asserted here. A mismatch means
//! the two emissions of the same .at source have drifted.
//!
//! Golden format (space-separated; fields never contain spaces):
//!   panelOfBlock <blockType> <kind> <tag> <class_token> <registry> <extension>
//!   panelHeading <level> <kind>
//!   isExtensionPanel <kind> <bool>
//!   builtinPanelKinds <k1,k2,...>
//!   extensionPanelKinds <k1,k2,...>

use autodown_core::palette_map::{
    builtinPanelKinds, extensionPanelKinds, isExtensionPanel, panelHeading, panelOfBlock,
};

/// Same probe set as the TS generator (kept in lockstep by the golden itself:
/// adding a probe there without regenerating fails here, and vice versa).
const BLOCK_TYPES: &[&str] = &[
    "paragraph",
    "text",
    "heading",
    "thematic_break",
    "code_block",
    "blockquote",
    "list",
    "table",
    "callout",
    "details",
    "math_block",
    "mermaid",
    "query",
    "embed",
    "no_such_block",
    "future_panel",
];
const LEVELS: &[i64] = &[-2, 0, 1, 2, 3, 4, 5, 6, 7, 100];
const EXTRA_KINDS: &[&str] = &["Unknown", "NotAKind"];

fn projection() -> Vec<String> {
    let mut lines = Vec::new();
    for bt in BLOCK_TYPES {
        let s = panelOfBlock(bt);
        lines.push(format!(
            "panelOfBlock {}",
            [
                (*bt).to_string(),
                s.kind.clone(),
                s.tag.clone(),
                s.class_token.clone(),
                s.registry.clone(),
                if s.extension { "true" } else { "false" }.to_string(),
            ]
            .join(" ")
        ));
    }
    for l in LEVELS {
        lines.push(format!("panelHeading {} {}", l, panelHeading(*l).kind));
    }
    let mut kinds: Vec<String> = EXTRA_KINDS.iter().map(|s| s.to_string()).collect();
    kinds.extend(builtinPanelKinds());
    kinds.extend(extensionPanelKinds());
    for k in &kinds {
        lines.push(format!(
            "isExtensionPanel {} {}",
            k,
            if isExtensionPanel(k) { "true" } else { "false" }
        ));
    }
    lines.push(format!("builtinPanelKinds {}", builtinPanelKinds().join(",")));
    lines.push(format!(
        "extensionPanelKinds {}",
        extensionPanelKinds().join(",")
    ));
    lines
}

#[test]
fn palette_map_matches_ts_golden() {
    let golden: Vec<&str> = include_str!("golden/palette-map.golden.txt")
        .lines()
        // header comments + blank lines are not part of the projection
        .filter(|l| !l.trim_start().starts_with('#') && !l.trim().is_empty())
        .collect();
    let golden: Vec<String> = golden.into_iter().map(str::to_string).collect();
    let proj = projection();
    assert_eq!(proj, golden, "rust a2r emission drifted from the TS golden");
}

#[test]
fn builtin_and_extension_kinds_are_disjoint() {
    for k in builtinPanelKinds() {
        assert!(!isExtensionPanel(&k), "builtin {k} must not be extension");
    }
    for k in extensionPanelKinds() {
        assert!(isExtensionPanel(&k), "extension {k} must be extension");
    }
}
