/**
 * @autodown/vue — markdown parser redirect.
 *
 * The incremental markdown parser moved to @autodown/core in plan 016
 * Phase 2 (packages/core/auto/markdown_parser.at -> core
 * src/markdown-parser.ts). This file is a hand-maintained compatibility
 * redirect so existing import sites keep working unchanged; it is NOT
 * regenerated by pnpm gen.
 */

export { parseDocument } from '@autodown/core'
