// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct TableAttr {
    pub cols: Vec<Option<i64>>,
    pub rows: Vec<Option<i64>>,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct PreDoc {
    pub md: String,
    pub tableAttrs: Vec<TableAttr>,
}

pub fn startsWithStr(s: &str, prefix: &str) -> bool {
    if (s.chars().count() as i64) < (prefix.chars().count() as i64) {
        return false;
    }
    return s.chars().take(((prefix.chars().count() as i64)) as usize).skip((0) as usize).collect::<String>() == prefix;
}

pub fn startsWithAt(s: &str, prefix: &str, at: i64) -> bool {
    if at < 0 {
        return false;
    }
    if at + (prefix.chars().count() as i64) > (s.chars().count() as i64) {
        return false;
    }
    return s.chars().take((at + (prefix.chars().count() as i64)) as usize).skip((at) as usize).collect::<String>() == prefix;
}

pub fn endsWithStr(s: &str, suffix: &str) -> bool {
    if (s.chars().count() as i64) < (suffix.chars().count() as i64) {
        return false;
    }
    return s.chars().take(((s.chars().count() as i64)) as usize).skip(((s.chars().count() as i64) - (suffix.chars().count() as i64)) as usize).collect::<String>() == suffix;
}

pub fn trimStartStr(s: &str) -> String {
    let mut p: i64 = 0;
    while p < (s.chars().count() as i64) {
        let c = s.chars().nth((p) as usize).unwrap_or('\0') as i64;
        if c == 32 {
            p += 1;
        } else {
            if c == 9 {
                p += 1;
            } else {
                break;
            }
        }

    }
    if p == 0 {
        return s.to_string();
    }
    return s.chars().skip((p) as usize).collect::<String>().to_string();
}

pub fn trimEndStr(s: &str) -> String {
    let mut end: i64 = (s.chars().count() as i64);
    while end > 0 {
        let c = s.chars().nth((end - 1) as usize).unwrap_or('\0') as i64;
        if c == 32 {
            end -= 1;
        } else {
            if c == 9 {
                end -= 1;
            } else {
                if c == 10 {
                    end -= 1;
                } else {
                    if c == 13 {
                        end -= 1;
                    } else {
                        break;
                    }
                }
            }
        }

    }
    if end == (s.chars().count() as i64) {
        return s.to_string();
    }
    return s.chars().take((end) as usize).skip((0) as usize).collect::<String>().to_string();
}

pub fn hasChar(s: &str, code: i64) -> bool {
    let mut i: i64 = 0;
    while i < (s.chars().count() as i64) {
        if s.chars().nth((i) as usize).unwrap_or('\0') as i64 == code {
            return true;
        }
        i += 1;
    }
    return false;
}

pub fn findStr(s: &str, needle: &str) -> i64 {
    if (needle.chars().count() as i64) == 0 {
        return 0;
    }
    if (s.chars().count() as i64) < (needle.chars().count() as i64) {
        return -1;
    }
    let mut i: i64 = 0;
    while i + (needle.chars().count() as i64) <= (s.chars().count() as i64) {
        if s.chars().take((i + (needle.chars().count() as i64)) as usize).skip((i) as usize).collect::<String>() == needle {
            return i;
        }
        i += 1;
    }
    return -1;
}

pub fn findStrFrom(s: &str, needle: &str, from: i64) -> i64 {
    if (needle.chars().count() as i64) == 0 {
        if from <= (s.chars().count() as i64) {
            return from;
        }        return -1;
    }
    let mut i: i64 = from;
    if i < 0 {
        i = 0;
    }
    while i + (needle.chars().count() as i64) <= (s.chars().count() as i64) {
        if s.chars().take((i + (needle.chars().count() as i64)) as usize).skip((i) as usize).collect::<String>() == needle {
            return i;
        }
        i += 1;
    }
    return -1;
}

pub fn rfindChar(s: &str, code: i64) -> i64 {
    let mut i: i64 = (s.chars().count() as i64) - 1;
    while i >= 0 {
        if s.chars().nth((i) as usize).unwrap_or('\0') as i64 == code {
            return i;
        }
        i -= 1;
    }
    return -1;
}

pub fn scanIntPrefix(s: &str) -> Option<i64> {
    let mut i: i64 = 0;
    let mut neg: bool = false;
    if (s.chars().count() as i64) > 0 {
        if s.chars().nth((0) as usize).unwrap_or('\0') as i64 == 45 {
            neg = true;
            i = 1;
        } else {
            if s.chars().nth((0) as usize).unwrap_or('\0') as i64 == 43 {
                i = 1;
            }        }
    }
    let mut val: i64 = 0;
    let mut digits: i64 = 0;
    while i < (s.chars().count() as i64) {
        let c = s.chars().nth((i) as usize).unwrap_or('\0') as i64;
        if c >= 48 {
            if c <= 57 {
                val = val * 10 + c - 48;
                digits += 1;
                i += 1;
            } else {
                break;
            }
        } else {
            break;
        }

    }
    if digits == 0 {
        return None;
    }
    if neg {
        val = -val;
    }
    return Some(val);
}

fn stripQuotes(s: &str) -> String {
    let t = s.trim().to_string();
    if (t.chars().count() as i64) == 0 {
        return t;
    }
    let mut start: i64 = 0;
    let mut end: i64 = (t.chars().count() as i64);
    let c0 = t.chars().nth((0) as usize).unwrap_or('\0') as i64;
    if c0 == 34 {
        start = 1;
    } else {
        if c0 == 39 {
            start = 1;
        }    }

    if end > start {
        let cl = t.chars().nth((end - 1) as usize).unwrap_or('\0') as i64;
        if cl == 34 {
            end = end - 1;
        } else {
            if cl == 39 {
                end = end - 1;
            }        }
    }
    return t.chars().take((end) as usize).skip((start) as usize).collect::<String>().to_string();
}

fn parseValue(s: &str) -> Option<i64> {
    let trimmed = stripQuotes(s);
    if trimmed == "auto" {
        return None;
    }
    return scanIntPrefix(trimmed.as_str());
}

fn parseArray(s: &str) -> Vec<Option<i64>> {
    let parts = s.split(",").map(|s| s.to_string()).collect::<Vec<String>>();
    let mut out: Vec<Option<i64>> = vec![];
    let mut i: i64 = 0;
    while i < (parts.len() as i64) {
        let p = parts[(i) as usize].clone();
        out.push(parseValue(p.as_str()));
        i += 1;
    }
    return out;
}

fn parseRows(mut s: Option<String>) -> Vec<Option<i64>> {
    let sv: String = s.unwrap_or("".to_string());
    if sv == "" {
        return vec![];
    }
    return parseArray(sv.as_str());
}

fn formatValue(mut v: Option<i64>) -> String {
    if v == None {
        return "\"auto\"".to_string();
    }
    return format!("{:?}", v.unwrap_or(0));
}

fn formatArray(arr: Vec<Option<i64>>) -> String {
    let mut parts: Vec<String> = vec![];
    for v in &arr {
        parts.push(formatValue(v.clone()));
    }
    return parts.join(",");
}

fn hasAnyValue(mut arr: Vec<Option<i64>>) -> bool {
    let mut i: i64 = 0;
    while i < (arr.len() as i64) {
        let v = arr[(i) as usize].clone();
        if v != None {
            return true;
        }
        i += 1;
    }
    return false;
}

fn isPipeRow(line: &str) -> bool {
    let mut end: i64 = (line.chars().count() as i64);
    while end > 0 {
        let c = line.chars().nth((end - 1) as usize).unwrap_or('\0') as i64;
        if c == 32 {
            end -= 1;
        } else {
            if c == 9 {
                end -= 1;
            } else {
                break;
            }
        }

    }
    if end < 2 {
        return false;
    }
    if line.chars().nth((0) as usize).unwrap_or('\0') as i64 != 124 {
        return false;
    }
    if line.chars().nth((end - 1) as usize).unwrap_or('\0') as i64 != 124 {
        return false;
    }
    return true;
}

fn isDelimRow(line: &str) -> bool {
    let mut end: i64 = (line.chars().count() as i64);
    while end > 0 {
        let c = line.chars().nth((end - 1) as usize).unwrap_or('\0') as i64;
        if c == 32 {
            end -= 1;
        } else {
            if c == 9 {
                end -= 1;
            } else {
                break;
            }
        }

    }
    if end < 3 {
        return false;
    }
    if line.chars().nth((0) as usize).unwrap_or('\0') as i64 != 124 {
        return false;
    }
    if line.chars().nth((end - 1) as usize).unwrap_or('\0') as i64 != 124 {
        return false;
    }
    let mut i: i64 = 1;
    while i < end - 1 {
        let c = line.chars().nth((i) as usize).unwrap_or('\0') as i64;
        let mut ok: bool = false;
        if c == 45 {
            ok = true;
        } else {
            if c == 58 {
                ok = true;
            } else {
                if c == 124 {
                    ok = true;
                } else {
                    if c == 32 {
                        ok = true;
                    } else {
                        if c == 9 {
                            ok = true;
                        }                    }
                }
            }
        }

        if !(ok) {
            return false;
        }
        i += 1;
    }
    return true;
}

fn parseIalLine(line: &str) -> Option<TableAttr> {
    let mut end: i64 = (line.chars().count() as i64);
    while end > 0 {
        let c = line.chars().nth((end - 1) as usize).unwrap_or('\0') as i64;
        if c == 32 {
            end -= 1;
        } else {
            if c == 9 {
                end -= 1;
            } else {
                break;
            }
        }

    }
    if end < 9 {
        return None;
    }
    let s = line.chars().take((end) as usize).skip((0) as usize).collect::<String>();
    if !(startsWithStr(s.as_str(), "{cols:[")) {
        return None;
    }
    if !(endsWithStr(s.as_str(), "}")) {
        return None;
    }
    let bodyEnd: i64 = (s.chars().count() as i64) - 1;
    let mut c1: i64 = -1;
    let mut i: i64 = 7;
    while i < bodyEnd {
        if s.chars().nth((i) as usize).unwrap_or('\0') as i64 == 93 {
            c1 = i;
            break;
        }
        i += 1;
    }
    if c1 == -1 {
        return None;
    }
    let cols = parseArray(s.chars().take((c1) as usize).skip((7) as usize).collect::<String>().as_str());
    let mut rows: Vec<Option<i64>> = vec![];
    let rest = s.chars().take((bodyEnd) as usize).skip((c1 + 1) as usize).collect::<String>();
    if rest != "" {
        if !(startsWithStr(rest.as_str(), ",")) {
            return None;
        }        let mut r = rest.chars().skip((1) as usize).collect::<String>();
        let mut advancing: bool = true;
        while advancing {
            advancing = false;
            if (r.chars().count() as i64) > 0 {
                let c = r.chars().nth((0) as usize).unwrap_or('\0') as i64;
                if c == 32 {
                    r = r.chars().skip((1) as usize).collect::<String>();
                    advancing = true;
                } else {
                    if c == 9 {
                        r = r.chars().skip((1) as usize).collect::<String>();
                        advancing = true;
                    } else {
                        if c == 10 {
                            r = r.chars().skip((1) as usize).collect::<String>();
                            advancing = true;
                        } else {
                            if c == 13 {
                                r = r.chars().skip((1) as usize).collect::<String>();
                                advancing = true;
                            }                        }
                    }
                }
            }
        }
        if !(startsWithStr(r.as_str(), "rows:[")) {
            return None;
        }        let r2 = r.chars().skip((6) as usize).collect::<String>();
        let mut c2: i64 = -1;
        let mut k: i64 = 0;
        while k < (r2.chars().count() as i64) {
            if r2.chars().nth((k) as usize).unwrap_or('\0') as i64 == 93 {
                c2 = k;
                break;
            }
            k += 1;
        }
        if c2 == -1 {
            return None;
        }        if c2 + 1 != (r2.chars().count() as i64) {
            return None;
        }        rows = parseArray(r2.chars().take((c2) as usize).skip((0) as usize).collect::<String>().as_str());
    }
    return Some(TableAttr { cols: cols, rows: rows });
}

pub fn preprocessMarkdown(md: &str) -> PreDoc {
    let lines = md.split("\n").map(|s| s.to_string()).collect::<Vec<String>>();
    let mut attrs: Vec<TableAttr> = vec![];
    let mut out: Vec<String> = vec![];
    let mut i: i64 = 0;
    while i < (lines.len() as i64) {
        let mut matched: bool = false;
        if i + 1 < (lines.len() as i64) {
            if isPipeRow(lines[(i) as usize].as_str()) {
                if isDelimRow(lines[(i + 1) as usize].as_str()) {
                    let mut j: i64 = i + 2;
                    let mut dataCount: i64 = 0;
                    let mut scanning: bool = true;
                    while scanning {
                        scanning = false;
                        if j < (lines.len() as i64) {
                            if isPipeRow(lines[(j) as usize].as_str()) {
                                j += 1;
                                dataCount += 1;
                                scanning = true;
                            }                        }
                    }
                    if dataCount >= 1 {
                        if j < (lines.len() as i64) {
                            let ial = parseIalLine(lines[(j) as usize].as_str());
                            if ial != None {
                                attrs.push(ial.unwrap_or(TableAttr { cols: vec![], rows: vec![] }));
                                let mut k: i64 = i;
                                while k < j {
                                    out.push(lines[(k) as usize].clone());
                                    k += 1;
                                }
                                i = j + 1;
                                matched = true;
                            }                        }                    }                }            }        }
        if !(matched) {
            out.push(lines[(i) as usize].clone());
            i += 1;
        }
    }
    return PreDoc { md: out.join("\n").to_string(), tableAttrs: attrs };
}

pub fn buildIAL(mut colwidth: Vec<Option<i64>>, mut rowheight: Vec<Option<i64>>) -> Option<String> {
    let hasCols = hasAnyValue(colwidth.clone());
    let hasRows = hasAnyValue(rowheight.clone());
    if !(hasCols) {
        if !(hasRows) {
            return None;
        }    }
    let mut parts: Vec<String> = vec![];
    if hasCols {
        parts.push(format!("{}{}", format!("{}{}", "cols:[", formatArray(colwidth.clone())), "]"));
    }
    if hasRows {
        parts.push(format!("{}{}", format!("{}{}", "rows:[", formatArray(rowheight.clone())), "]"));
    }
    return Some(format!("{}{}", format!("{}{}", "{", parts.join(", ")), "}\n"));
}
