// Auto-generated by a2r transpiler

use crate::block_model::{BlockNode, BlockType, InlineSpan, Mark, Attr, Value, attrGet, attrGetStr, attrGetInt, attrGetBool, hasMark, spansText};
pub fn repeatStr(s: &str, n: i64) -> String {
    let mut out: String = "".to_string();
    for i in 0..n {
        out = format!("{}{}", out, s);
    }
    return out;
}

pub fn endsWith(hay: &str, needle: &str) -> bool {
    let hl: i64 = (hay.chars().count() as i64);
    let nl: i64 = (needle.chars().count() as i64);
    if hl < nl {
        return false;
    }
    return hay.chars().take((hl) as usize).skip((hl - nl) as usize).collect::<String>() == needle;
}

pub fn hasNewline(s: &str) -> bool {
    for i in 0..(s.chars().count() as i64) {
        if s.chars().take((i + 1) as usize).skip((i) as usize).collect::<String>() == "\n" {
            return true;
        }
    }
    return false;
}

pub fn spanMd(mut s: InlineSpan) -> String {


    if s.text == "\n" {
        return "  \n".to_string();
    }
    let mut t: String = s.text.clone();
    if hasMark(s.marks.clone(), Mark::Code.clone()) {
        t = format!("{}{}", format!("{}{}", "`", t), "`");
    }
    if hasMark(s.marks.clone(), Mark::Strong.clone()) {
        t = format!("{}{}", format!("{}{}", "**", t), "**");
    }
    if hasMark(s.marks.clone(), Mark::Em.clone()) {
        t = format!("{}{}", format!("{}{}", "*", t), "*");
    }
    if hasMark(s.marks.clone(), Mark::Underline.clone()) {
        t = format!("{}{}", format!("{}{}", "__", t), "__");
    }
    if hasMark(s.marks.clone(), Mark::Del.clone()) {
        t = format!("{}{}", format!("{}{}", "~~", t), "~~");
    }
    if hasMark(s.marks.clone(), Mark::Link.clone()) {
        let href = attrGetStr(s.attrs.clone(), "href", "");
        let title = attrGetStr(s.attrs.clone(), "title", "");
        if (title.chars().count() as i64) > 0 {
            t = format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", "[", t), "]("), href), " \""), title), "\")");
        } else {
            t = format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", "[", t), "]("), href), ")");
        }
    }
    if hasMark(s.marks.clone(), Mark::Image.clone()) {
        let src = attrGetStr(s.attrs.clone(), "src", "");
        let ititle = attrGetStr(s.attrs.clone(), "title", "");
        if (ititle.chars().count() as i64) > 0 {
            t = format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", "![", t), "]("), src), " \""), ititle), "\")");
        } else {
            t = format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", "![", t), "]("), src), ")");
        }
    }
    return t;
}

pub fn inlinesMd(spans: Vec<InlineSpan>) -> String {
    let mut out: String = "".to_string();
    for s in &spans {
        out = format!("{}{}", out, spanMd(s.clone()));
    }
    return out;
}

pub fn alignMarker(align: &str) -> String {
    if align == "left" {
        return ":---".to_string();
    }
    if align == "center" {
        return ":---:".to_string();
    }
    if align == "right" {
        return "---:".to_string();
    }
    return "---".to_string();
}

pub fn tableRowMd(row: BlockNode) -> String {
    let mut out: String = "|".to_string();
    for c in &row.children {
        out = format!("{}{}", format!("{}{}", format!("{}{}", out, " "), inlinesMd(c.inlines.clone())), " |");
    }
    return out;
}

pub fn tableDelimMd(headerRow: BlockNode) -> String {
    let mut out: String = "|".to_string();
    for c in &headerRow.children {
        out = format!("{}{}", format!("{}{}", format!("{}{}", out, " "), alignMarker(attrGetStr(c.attrs.clone(), "align", "").as_str())), " |");
    }
    return out;
}

pub fn listOfValue(v: Value) -> Vec<Value> {
    match v {
        Value::Null => return vec![],
        Value::Str(s) => return vec![],
        Value::Int(i) => return vec![],
        Value::Bool(b) => return vec![],
        Value::ListV(l) => return l,
        Value::AttrsV(m) => return vec![],
    };
    return vec![];
}

pub fn attrsOfValue(v: Value) -> Vec<Attr> {
    match v {
        Value::Null => return vec![],
        Value::Str(s) => return vec![],
        Value::Int(i) => return vec![],
        Value::Bool(b) => return vec![],
        Value::ListV(l) => return vec![],
        Value::AttrsV(m) => return m,
    };
    return vec![];
}

pub fn intOfValue(v: Value) -> Option<i64> {
    match v {
        Value::Null => return None,
        Value::Str(s) => return None,
        Value::Int(i) => return Some(i),
        Value::Bool(b) => return None,
        Value::ListV(l) => return None,
        Value::AttrsV(m) => return None,
    };
    return None;
}

pub fn valueToIntList(mut v: Value) -> Vec<Option<i64>> {
    let items = listOfValue(v.clone());
    let mut out: Vec<Option<i64>> = vec![];
    for i in 0..(items.len() as i64) {
        out.push(intOfValue(items[(i) as usize].clone()));
    }
    return out;
}

pub fn hasAnyInt(mut arr: Vec<Option<i64>>) -> bool {
    for i in 0..(arr.len() as i64) {
        if arr[(i) as usize].clone() != None {
            return true;
        }
    }
    return false;
}

pub fn formatIntList(mut arr: Vec<Option<i64>>) -> String {
    let mut out: String = "".to_string();
    for i in 0..(arr.len() as i64) {
        if i > 0 {
            out = format!("{}{}", out, ",");
        }
        let v = arr[(i) as usize].clone();
        if v == None {
            out = format!("{}{}", out, "\"auto\"");
        } else {
            let n: i64 = v.unwrap_or(0);
            out = format!("{}{}", out, format!("{:?}", n));
        }

    }
    return out;
}

pub fn ialText(mut ialAttrs: Vec<Attr>) -> String {
    let colsFound = attrGet(ialAttrs.clone(), "cols");
    let rowsFound = attrGet(ialAttrs.clone(), "rows");
    let cols = valueToIntList(colsFound.unwrap_or(Value::Null));
    let rows = valueToIntList(rowsFound.unwrap_or(Value::Null));
    let mut parts: Vec<String> = vec![];
    if hasAnyInt(cols.clone()) {
        parts.push(format!("{}{}", format!("{}{}", "cols:[", formatIntList(cols.clone())), "]"));
    }
    if hasAnyInt(rows.clone()) {
        parts.push(format!("{}{}", format!("{}{}", "rows:[", formatIntList(rows.clone())), "]"));
    }
    let mut out: String = "".to_string();
    for i in 0..(parts.len() as i64) {
        if i > 0 {
            out = format!("{}{}", out, ", ");
        }
        out = format!("{}{}", out, parts[(i) as usize].clone());
    }
    return out;
}

pub fn tableMd(node: BlockNode) -> String {
    if (node.children.len() as i64) == 0 {
        return "".to_string();
    }
    let mut out: String = "".to_string();
    for i in 0..(node.children.len() as i64) {
        if i > 0 {
            out = format!("{}{}", out, "\n");
        }
        let row = node.children[(i) as usize].clone();
        if i == 0 {
            out = format!("{}{}", format!("{}{}", format!("{}{}", out, tableRowMd(row.clone())), "\n"), tableDelimMd(row.clone()));
        } else {
            out = format!("{}{}", out, tableRowMd(row.clone()));
        }

    }
    let ialFound = attrGet(node.attrs.clone(), "ial");
    if ialFound != None {
        let body = ialText(attrsOfValue(ialFound.unwrap_or(Value::Null)));
        if (body.chars().count() as i64) > 0 {
            out = format!("{}{}", format!("{}{}", format!("{}{}", out, "\n{"), body), "}");
        }    }
    return out;
}

pub fn joinChildren(mut kids: Vec<BlockNode>, withId: bool) -> String {
    let mut out: String = "".to_string();
    for i in 0..(kids.len() as i64) {
        if i > 0 {
            if kids[(i) as usize].clone().kind == BlockType::ListBlock {
                out = format!("{}{}", out, "\n");
            } else {
                out = format!("{}{}", out, "\n\n");
            }
        }
        out = format!("{}{}", out, blockMd(kids[(i) as usize].clone(), withId));
    }
    return out;
}

pub fn quoteMd(node: BlockNode, withId: bool) -> String {
    let body = joinChildren(node.children.clone(), withId);
    let lines = body.split("\n").map(|s| s.to_string()).collect::<Vec<String>>();
    let mut out: String = "".to_string();
    for i in 0..(lines.len() as i64) {
        if i > 0 {
            out = format!("{}{}", out, "\n");
        }
        if (lines[(i) as usize].clone().len() as i64) > 0 {
            out = format!("{}{}", format!("{}{}", out, "> "), lines[(i) as usize].clone());
        } else {
            out = format!("{}{}", out, ">");
        }

    }
    return out;
}

pub fn listMd(node: BlockNode, withId: bool) -> String {
    let ordered = attrGetBool(node.attrs.clone(), "ordered", false);
    let start = attrGetInt(node.attrs.clone(), "start", 1);
    let mut out: String = "".to_string();
    for i in 0..(node.children.len() as i64) {
        if i > 0 {
            out = format!("{}{}", out, "\n");
        }
        let mut marker: String = "- ".to_string();
        if ordered {
            let n: i64 = start + i;
            marker = format!("{}{}", format!("{:?}", n), ". ");
        }
        let body = joinChildren(node.children[(i) as usize].clone().children.clone(), withId);
        let lines = body.split("\n").map(|s| s.to_string()).collect::<Vec<String>>();
        let pad = repeatStr(" ", (marker.chars().count() as i64));
        for j in 0..(lines.len() as i64) {
            if j > 0 {
                out = format!("{}{}", out, "\n");
            }
            if j == 0 {
                out = format!("{}{}", format!("{}{}", out, marker), lines[(j) as usize].clone());
            } else {
                if (lines[(j) as usize].clone().len() as i64) > 0 {
                    out = format!("{}{}", format!("{}{}", out, pad), lines[(j) as usize].clone());
                }            }

        }
    }
    return out;
}

pub fn fenceMd(node: BlockNode) -> String {
    let lang = attrGetStr(node.attrs.clone(), "language", "");
    let code = spansText(node.inlines.clone());
    let mut out: String = format!("{}{}", format!("{}{}", format!("{}{}", "```", lang), "\n"), code);
    if (code.chars().count() as i64) > 0 {
        if !(endsWith(code.as_str(), "\n")) {
            out = format!("{}{}", out, "\n");
        }    }
    out = format!("{}{}", out, "```");
    return out;
}

pub fn headingMd(node: BlockNode, withId: bool) -> String {
    let level = attrGetInt(node.attrs.clone(), "level", 1);
    let mut t: String = inlinesMd(node.inlines.clone());
    if withId {
        t = withIdSuffix(t.as_str(), attrGetStr(node.attrs.clone(), "anchor", "").as_str());
    }
    if level <= 2 {
        if hasNewline(t.as_str()) {
            let mut underline: String = "---".to_string();
            if level == 1 {
                underline = "===".to_string();
            }            return format!("{}{}", format!("{}{}", t, "\n"), underline);
        }    }
    return format!("{}{}", format!("{}{}", repeatStr("#", level), " "), t);
}

pub fn componentBlockMd(name: &str, argName: &str, node: BlockNode, withId: bool) -> String {
    let arg = attrGetStr(node.attrs.clone(), argName, "");
    return format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", "$", name), "("), argName), ": \""), arg), "\") {\n"), joinChildren(node.children.clone(), withId)), "\n}");
}

pub fn detailsMd(node: BlockNode, withId: bool) -> String {
    let summary = attrGetStr(node.attrs.clone(), "summary", "");
    let mut open: String = "".to_string();
    if attrGetBool(node.attrs.clone(), "open", false) {
        open = ", open: true".to_string();
    }
    return format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", "$details(summary: \"", summary), "\""), open), ") {\n"), joinChildren(node.children.clone(), withId)), "\n}");
}

pub fn wikilinkMd(node: BlockNode) -> String {
    let target = attrGetStr(node.attrs.clone(), "target", "");
    let anchor = attrGetStr(node.attrs.clone(), "anchor", "");
    if (anchor.chars().count() as i64) > 0 {
        return format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", "[[", target), "#"), anchor), "]]");
    }
    return format!("{}{}", format!("{}{}", "[[", target), "]]");
}

pub fn blockMd(mut node: BlockNode, withId: bool) -> String {
    let k = node.kind.clone();
    if k == BlockType::Heading {
        return headingMd(node.clone(), withId);
    }
    if k == BlockType::Fence {
        return fenceMd(node.clone());
    }
    if k == BlockType::Blockquote {
        return quoteMd(node.clone(), withId);
    }
    if k == BlockType::ListBlock {
        return listMd(node.clone(), withId);
    }
    if k == BlockType::ListItem {
        return joinChildren(node.children.clone(), withId);
    }
    if k == BlockType::Table {
        return tableMd(node.clone());
    }
    if k == BlockType::TableRow {
        return tableRowMd(node.clone());
    }
    if k == BlockType::TableCell {
        return inlinesMd(node.inlines.clone());
    }
    if k == BlockType::ThematicBreak {
        return "---".to_string();
    }
    if k == BlockType::Callout {
        return componentBlockMd("callout", "type", node.clone(), withId);
    }
    if k == BlockType::Details {
        return detailsMd(node.clone(), withId);
    }
    if k == BlockType::WikilinkBlock {
        return wikilinkMd(node.clone());
    }
    if k == BlockType::QueryBlock {
        return format!("{}{}", format!("{}{}", "$query(", attrGetStr(node.attrs.clone(), "query", "")), ")");
    }
    if k == BlockType::BlockEmbed {
        return format!("{}{}", format!("{}{}", "$embed(src: \"", attrGetStr(node.attrs.clone(), "src", "")), "\")");
    }
    if k == BlockType::Mermaid {
        return format!("{}{}", format!("{}{}", "```mermaid\n", spansText(node.inlines.clone())), "\n```");
    }
    if k == BlockType::MathBlock {
        return format!("{}{}", format!("{}{}", "%{\n", spansText(node.inlines.clone())), "\n}%");
    }

    let t = inlinesMd(node.inlines.clone());
    if withId {
        return withIdSuffix(t.as_str(), attrGetStr(node.attrs.clone(), "anchor", "").as_str());
    }
    return t;
}

pub fn withIdSuffix(text: &str, id: &str) -> String {
    let tok: String = format!("{}{}", "^", id);
    if (id.chars().count() as i64) == 0 {
        return text.to_string();
    }
    if endsWith(text, tok.as_str()) {
        return text.to_string();
    }
    return format!("{}{}", format!("{}{}", text, " "), tok);
}

pub fn serializeBlocks(mut blocks: Vec<BlockNode>, emitIds: bool) -> String {
    let mut out: String = "".to_string();
    for i in 0..(blocks.len() as i64) {
        if i > 0 {
            out = format!("{}{}", out, "\n\n");
        }
        let b = blocks[(i) as usize].clone();
        

        out = format!("{}{}", out, blockMd(b.clone(), emitIds));
    }
    return out;
}

pub fn serialize(root: BlockNode, emitIds: bool) -> String {
    let body = serializeBlocks(root.children.clone(), emitIds);
    if (body.chars().count() as i64) == 0 {
        return "".to_string();
    }
    return format!("{}{}", body, "\n");
}
