// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct LgPage {
    pub path: String,
    pub title: String,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct LgAlias {
    pub tagName: String,
    pub pagePath: String,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct LgLink {
    pub sourcePage: String,
    pub targetPage: String,
    pub context: String,
    pub sourceBlockUuid: String,
    pub targetBlockUuid: String,
    pub linkType: String,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct LgBacklink {
    pub sourcePage: String,
    pub sourceBlockUuid: String,
    pub context: String,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct LgOutlink {
    pub targetPage: String,
    pub targetBlockUuid: String,
    pub linkType: String,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct LgNode {
    pub id: String,
    pub label: String,
    pub path: String,
    pub exists: bool,
    pub degree: i64,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct LgEdge {
    pub source: String,
    pub target: String,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct LgGraph {
    pub nodes: Vec<LgNode>,
    pub edges: Vec<LgEdge>,
}

fn asciiLower(s: &str) -> String {
    let mut out: String = "".to_string();
    let lower: String = "abcdefghijklmnopqrstuvwxyz".to_string();
    let mut i: i64 = 0;
    while i < (s.chars().count() as i64) {
        let c = s.chars().nth((i) as usize).unwrap_or('\0') as i64;
        if c >= 65 && c <= 90 {
            out = format!("{}{}", out, lower.chars().take((c - 64) as usize).skip((c - 65) as usize).collect::<String>());
        } else {
            out = format!("{}{}", out, s.chars().take((i + 1) as usize).skip((i) as usize).collect::<String>());
        }

        i += 1;
    }
    return out;
}

fn eqIgnoreCase(a: &str, b: &str) -> bool {
    return asciiLower(a) == asciiLower(b);
}

/// Lexicographic comparison by char code (rust String::cmp byte order is
/// code-point order for BMP content).
fn strCompare(a: &str, b: &str) -> i64 {
    let n: i64 = (a.chars().count() as i64);
    let m: i64 = (b.chars().count() as i64);
    let mut minLen: i64 = n;
    if m < n {
        minLen = m;
    }
    let mut i: i64 = 0;
    while i < minLen {
        let ca = a.chars().nth((i) as usize).unwrap_or('\0') as i64;
        let cb = b.chars().nth((i) as usize).unwrap_or('\0') as i64;
        if ca < cb {
            return -1;
        }
        if ca > cb {
            return 1;
        }
        i += 1;
    }
    if n < m {
        return -1;
    }
    if n > m {
        return 1;
    }
    return 0;
}

pub fn resolvePagePath(pages: Vec<LgPage>, aliases: Vec<LgAlias>, title: &str) -> String {
    for p in &pages {
        if eqIgnoreCase(p.title.as_str(), title) {
            

            return format!("{}{}", "", p.path);
        }
    }
    for a in &aliases {
        if eqIgnoreCase(a.tagName.as_str(), title) {
            return format!("{}{}", "", a.pagePath);
        }
    }
    return "".to_string();
}

fn canonicalTitleOf(pages: Vec<LgPage>, path: &str) -> String {
    for p in &pages {
        if p.path == path {
            return format!("{}{}", "", p.title);
        }
    }
    return "".to_string();
}

fn sortBacklinks(items: Vec<LgBacklink>) -> Vec<LgBacklink> {
    let mut out: Vec<LgBacklink> = vec![];
    for it in &items {
        let mut inserted: bool = false;
        let mut res: Vec<LgBacklink> = vec![];
        for e in &out {
            if !(inserted) && strCompare(it.sourcePage.as_str(), e.sourcePage.as_str()) < 0 {
                res.push(it.clone().clone());
                inserted = true;
            }
            res.push(e.clone().clone());
        }
        if !(inserted) {
            res.push(it.clone().clone());
        }
        out = res.clone();
    }
    return out;
}

fn sortOutlinks(items: Vec<LgOutlink>) -> Vec<LgOutlink> {
    let mut out: Vec<LgOutlink> = vec![];
    for it in &items {
        let mut inserted: bool = false;
        let mut res: Vec<LgOutlink> = vec![];
        for e in &out {
            if !(inserted) && strCompare(it.targetPage.as_str(), e.targetPage.as_str()) < 0 {
                res.push(it.clone().clone());
                inserted = true;
            }
            res.push(e.clone().clone());
        }
        if !(inserted) {
            res.push(it.clone().clone());
        }
        out = res.clone();
    }
    return out;
}

pub fn backlinksOf(mut pages: Vec<LgPage>, mut aliases: Vec<LgAlias>, links: Vec<LgLink>, title: &str) -> Vec<LgBacklink> {
    let mut out: Vec<LgBacklink> = vec![];
    let targetPath = resolvePagePath(pages.clone(), aliases.clone(), title);
    if targetPath == "" {
        return out;
    }
    let canonical = canonicalTitleOf(pages.clone(), targetPath.as_str());
    if canonical == "" {
        return out;
    }
    for l in &links {
        if l.targetPage != "" {
            if eqIgnoreCase(l.targetPage.as_str(), canonical.as_str()) {
                out.push(LgBacklink { sourcePage: l.sourcePage.clone().to_string(), sourceBlockUuid: l.sourceBlockUuid.clone().to_string(), context: l.context.clone().to_string() });
            }        }
    }
    return sortBacklinks(out.clone());
}

pub fn outlinksOf(mut pages: Vec<LgPage>, mut aliases: Vec<LgAlias>, links: Vec<LgLink>, title: &str) -> Vec<LgOutlink> {
    let mut out: Vec<LgOutlink> = vec![];
    let source = resolvePagePath(pages.clone(), aliases.clone(), title);
    if source == "" {
        return out;
    }
    for l in &links {
        if l.sourcePage == source {
            out.push(LgOutlink { targetPage: l.targetPage.clone().to_string(), targetBlockUuid: l.targetBlockUuid.clone().to_string(), linkType: l.linkType.clone().to_string() });
        }
    }
    return sortOutlinks(out.clone());
}

fn nodeKnown(nodes: Vec<LgNode>, id: &str) -> bool {
    for n in &nodes {
        if n.id == id {
            return true;
        }
    }
    return false;
}

fn sortNodes(items: Vec<LgNode>) -> Vec<LgNode> {
    let mut out: Vec<LgNode> = vec![];
    for it in &items {
        let mut inserted: bool = false;
        let mut res: Vec<LgNode> = vec![];
        for e in &out {
            if !(inserted) && strCompare(it.id.as_str(), e.id.as_str()) < 0 {
                res.push(it.clone().clone());
                inserted = true;
            }
            res.push(e.clone().clone());
        }
        if !(inserted) {
            res.push(it.clone().clone());
        }
        out = res.clone();
    }
    return out;
}

pub fn graphData(mut pages: Vec<LgPage>, mut aliases: Vec<LgAlias>, links: Vec<LgLink>) -> LgGraph {


    let mut nodes: Vec<LgNode> = vec![];
    for p in &pages {
        nodes.push(LgNode { id: p.path.clone().to_string(), label: p.title.clone().to_string(), path: p.path.clone().to_string(), exists: true, degree: 0 });
    }
    nodes = sortNodes(nodes.clone());

    let mut edges: Vec<LgEdge> = vec![];
    for l in &links {
        if l.targetPage != "" {
            let targetPath = resolvePagePath(pages.clone(), aliases.clone(), l.targetPage.as_str());
            if targetPath != "" {
                let sourceId = l.sourcePage.clone();
                let targetId = targetPath.to_string();
                if nodeKnown(nodes.clone(), sourceId.as_str()) && nodeKnown(nodes.clone(), targetId.as_str()) {
                    edges.push(LgEdge { source: sourceId.to_string(), target: targetId.to_string() });
                }            }        }
    }



    let mut out: Vec<LgNode> = vec![];
    for n in &nodes {
        let mut degree: i64 = 0;
        for e in &edges {
            if e.source == n.id {
                degree += 1;
            }
            if e.target == n.id {
                degree += 1;
            }
        }
        out.push(LgNode { id: n.id.clone().to_string(), label: n.label.clone().to_string(), path: n.path.clone().to_string(), exists: n.exists.clone(), degree: degree });
    }
    return LgGraph { nodes: out, edges: edges };
}
