// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct LineBlock {
    pub uuid: String,
    pub lineStart: i64,
    pub lineEnd: i64,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct WikiLinkHit {
    pub title: String,
    pub blockId: String,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct LinkScan {
    pub sourcePage: String,
    pub sourceBlockUuid: String,
    pub targetPage: String,
    pub targetBlockUuid: String,
    pub linkType: String,
    pub context: String,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct TagScan {
    pub pagePath: String,
    pub tag: String,
    pub blockUuid: String,
}

fn startsWithStr(s: &str, prefix: &str) -> bool {
    if (s.chars().count() as i64) < (prefix.chars().count() as i64) {
        return false;
    }
    return s.chars().take(((prefix.chars().count() as i64)) as usize).skip((0) as usize).collect::<String>() == prefix;
}

fn trimStr(s: &str) -> String {
    return trimStartStr(trimEndStr(s).as_str());
}

fn isWs(c: i64) -> bool {
    if c == 32 {
        return true;
    }
    if c == 9 {
        return true;
    }
    if c == 10 {
        return true;
    }
    if c == 13 {
        return true;
    }
    if c == 11 {
        return true;
    }
    if c == 12 {
        return true;
    }
    return false;
}

fn trimStartStr(s: &str) -> String {
    let mut p: i64 = 0;
    while p < (s.chars().count() as i64) {
        if !(isWs(s.chars().nth((p) as usize).unwrap_or('\0') as i64)) {
            break;
        }
        p += 1;
    }
    if p == 0 {
        return s.to_string();
    }
    return s.chars().skip((p) as usize).collect::<String>().to_string();
}

fn trimEndStr(s: &str) -> String {
    let mut end: i64 = (s.chars().count() as i64);
    while end > 0 {
        if !(isWs(s.chars().nth((end - 1) as usize).unwrap_or('\0') as i64)) {
            break;
        }
        end -= 1;
    }
    if end == (s.chars().count() as i64) {
        return s.to_string();
    }
    return s.chars().take((end) as usize).skip((0) as usize).collect::<String>().to_string();
}

fn isHexChar(c: i64) -> bool {
    if c >= 48 && c <= 57 {
        return true;
    }
    if c >= 65 && c <= 70 {
        return true;
    }
    if c >= 97 && c <= 102 {
        return true;
    }
    return false;
}

fn isUuid36(s: &str) -> bool {
    if (s.chars().count() as i64) != 36 {
        return false;
    }
    let mut i: i64 = 0;
    while i < 36 {
        let c = s.chars().nth((i) as usize).unwrap_or('\0') as i64;
        if i == 8 || i == 13 || i == 18 || i == 23 {
            if c != 45 {
                return false;
            }        } else {
            if !(isHexChar(c)) {
                return false;
            }        }

        i += 1;
    }
    return true;
}

fn isLinkBreakChar(c: i64) -> bool {
    if c == 93 {
        return true;
    }
    if c == 124 {
        return true;
    }
    if c == 35 {
        return true;
    }
    if c == 10 {
        return true;
    }
    return false;
}

pub fn scanWikiLinksLine(line: &str) -> Vec<WikiLinkHit> {
    let mut out: Vec<WikiLinkHit> = vec![];
    let n: i64 = (line.chars().count() as i64);
    let mut i: i64 = 0;
    while i + 1 < n {
        if line.chars().nth((i) as usize).unwrap_or('\0') as i64 == 91 && line.chars().nth((i + 1) as usize).unwrap_or('\0') as i64 == 91 {
            

            let mut j: i64 = i + 2;
            while j < n {
                let c = line.chars().nth((j) as usize).unwrap_or('\0') as i64;
                if isLinkBreakChar(c) {
                    break;
                }
                j += 1;
            }
            let titleEnd: i64 = j;
            let mut blockStart: i64 = -1;
            if line.chars().nth((j) as usize).unwrap_or('\0') as i64 == 35 {
                blockStart = j;
                j += 1;
                while j < n {
                    let c = line.chars().nth((j) as usize).unwrap_or('\0') as i64;
                    if c == 93 || c == 124 || c == 10 {
                        break;
                    }
                    j += 1;
                }
            }            if j + 1 < n && line.chars().nth((j) as usize).unwrap_or('\0') as i64 == 93 && line.chars().nth((j + 1) as usize).unwrap_or('\0') as i64 == 93 {
                let title = trimStr(line.chars().take((titleEnd) as usize).skip((i + 2) as usize).collect::<String>().as_str());
                if (title.chars().count() as i64) > 0 {
                    let mut bid: String = "".to_string();
                    if blockStart >= 0 {
                        bid = line.chars().take((j) as usize).skip((blockStart + 1) as usize).collect::<String>();
                    }                    out.push(WikiLinkHit { title: title.to_string(), blockId: bid.to_string() });
                    i = j + 2;
                } else {
                    i += 1;
                }
            } else {
                i += 1;
            }
        } else {
            i += 1;
        }

    }
    return out;
}

pub fn scanBlockRefsLine(line: &str) -> Vec<String> {
    let mut out: Vec<String> = vec![];
    let n: i64 = (line.chars().count() as i64);
    let mut i: i64 = 0;
    while i + 1 < n {
        if line.chars().nth((i) as usize).unwrap_or('\0') as i64 == 40 && line.chars().nth((i + 1) as usize).unwrap_or('\0') as i64 == 40 {
            let mut j: i64 = i + 2;
            while j < n {
                let c = line.chars().nth((j) as usize).unwrap_or('\0') as i64;
                if c == 41 {
                    break;
                }
                j += 1;
            }
            if j + 1 < n && line.chars().nth((j) as usize).unwrap_or('\0') as i64 == 41 && line.chars().nth((j + 1) as usize).unwrap_or('\0') as i64 == 41 {
                let cand = line.chars().take((j) as usize).skip((i + 2) as usize).collect::<String>();
                if isUuid36(cand.as_str()) {
                    out.push(cand.to_string());
                    i = j + 2;
                } else {
                    i += 1;
                }
            } else {
                i += 1;
            }
        } else {
            i += 1;
        }

    }
    return out;
}

/// Scan one line for "[[title]]" / "[[title#block]]" hits. Mirrors
/// WIKI_LINK_RE captures (trimmed title, optional block id).
/// Scan one line for "((uuid36))" block references (Logseq style).
fn isTagChar(c: i64) -> bool {
    if c >= 48 && c <= 57 {
        return true;
    }
    if c >= 65 && c <= 90 {
        return true;
    }
    if c >= 97 && c <= 122 {
        return true;
    }
    if c == 45 {
        return true;
    }
    if c == 95 {
        return true;
    }
    if c == 47 {
        return true;
    }
    return false;
}

pub fn scanTagsLine(line: &str) -> Vec<String> {
    let mut out: Vec<String> = vec![];
    let n: i64 = (line.chars().count() as i64);
    let mut i: i64 = 0;
    while i < n {
        if line.chars().nth((i) as usize).unwrap_or('\0') as i64 == 35 {
            let mut j: i64 = i + 1;
            while j < n {
                if !(isTagChar(line.chars().nth((j) as usize).unwrap_or('\0') as i64)) {
                    break;
                }
                j += 1;
            }
            if j > i + 1 {
                out.push(line.chars().take((j) as usize).skip((i + 1) as usize).collect::<String>());
                i = j;
            } else {
                i += 1;
            }
        } else {
            i += 1;
        }

    }
    return out;
}

/// Scan one line for "#tag" runs (TAG_RE: #([A-Za-z0-9_/-]+)).
fn findBlockUuidForLine(mut blocks: Vec<LineBlock>, idx: i64) -> String {
    let mut i: i64 = 0;
    while i < (blocks.len() as i64) {
        let b = blocks[(i) as usize].clone();
        if b.lineStart <= idx && idx < b.lineEnd {
            return b.uuid;
        }
        i += 1;
    }
    return "".to_string();
}

fn bodyLineCount(mut lines: Vec<String>) -> i64 {

    let mut count: i64 = (lines.len() as i64);
    if count > 0 {
        if lines[(count - 1) as usize].clone() == "" {
            count -= 1;
        }    }
    return count;
}

pub fn scanLinkRows(body: &str, sourcePage: &str, mut blocks: Vec<LineBlock>) -> Vec<LinkScan> {
    let mut rows: Vec<LinkScan> = vec![];
    let lines = body.split("\n").map(|s| s.to_string()).collect::<Vec<String>>();
    let count = bodyLineCount(lines.clone());
    let mut idx: i64 = 0;
    while idx < count {
        let context = trimStr(lines[(idx) as usize].as_str());
        let sbu = findBlockUuidForLine(blocks.clone(), idx);
        let wikiHits = scanWikiLinksLine(lines[(idx) as usize].as_str());
        let mut w: i64 = 0;
        while w < (wikiHits.len() as i64) {
            rows.push(LinkScan { sourcePage: sourcePage.to_string(), sourceBlockUuid: sbu.to_string(), targetPage: wikiHits[(w) as usize].clone().title.to_string(), targetBlockUuid: wikiHits[(w) as usize].clone().blockId.to_string(), linkType: "page".to_string(), context: context.to_string() });
            w += 1;
        }
        let refHits = scanBlockRefsLine(lines[(idx) as usize].as_str());
        let mut r: i64 = 0;
        while r < (refHits.len() as i64) {
            rows.push(LinkScan { sourcePage: sourcePage.to_string(), sourceBlockUuid: sbu.to_string(), targetPage: "".to_string(), targetBlockUuid: refHits[(r) as usize].clone().to_string(), linkType: "block".to_string(), context: context.to_string() });
            r += 1;
        }
        idx += 1;
    }
    return rows;
}

pub fn scanTagRows(body: &str, pagePath: &str, mut blocks: Vec<LineBlock>) -> Vec<TagScan> {
    let mut rows: Vec<TagScan> = vec![];
    let lines = body.split("\n").map(|s| s.to_string()).collect::<Vec<String>>();
    let count = bodyLineCount(lines.clone());
    let mut idx: i64 = 0;
    while idx < count {
        let bu = findBlockUuidForLine(blocks.clone(), idx);
        let hits = scanTagsLine(lines[(idx) as usize].as_str());
        let mut t: i64 = 0;
        while t < (hits.len() as i64) {
            rows.push(TagScan { pagePath: pagePath.to_string(), tag: hits[(t) as usize].clone().to_string(), blockUuid: bu.to_string() });
            t += 1;
        }
        idx += 1;
    }
    return rows;
}
