// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct QueryTask {
    pub title: String,
    pub content: String,
    pub marker: String,
    pub priority: String,
    pub scheduled: String,
    pub deadline: String,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct QueryEvalOut {
    pub ok: bool,
    pub err: String,
    pub value: bool,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct QueryEvalOut2 {
    pub ok: bool,
    pub err: String,
    pub days: i64,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct OffsetDays {
    pub ok: bool,
    pub err: String,
    pub days: i64,
}

fn evalOut(value: bool) -> QueryEvalOut {
    return QueryEvalOut { ok: true, err: "".to_string(), value: value };
}

fn evalErr(err: &str) -> QueryEvalOut {
    return QueryEvalOut { ok: false, err: err.to_string(), value: false };
}

fn notBool(b: bool) -> bool {
    if b {
        return false;
    }
    return true;
}

fn dblOpenBrace() -> String {
    return format!("{}{}", "{", "{");
}

fn dblCloseBrace() -> String {
    return format!("{}{}", "}", "}");
}

fn startsWithStr(s: &str, prefix: &str) -> bool {
    if (s.chars().count() as i64) < (prefix.chars().count() as i64) {
        return false;
    }
    return s.chars().take(((prefix.chars().count() as i64)) as usize).skip((0) as usize).collect::<String>() == prefix;
}

fn endsWithStr(s: &str, suffix: &str) -> bool {
    if (s.chars().count() as i64) < (suffix.chars().count() as i64) {
        return false;
    }
    return s.chars().take(((s.chars().count() as i64)) as usize).skip(((s.chars().count() as i64) - (suffix.chars().count() as i64)) as usize).collect::<String>() == suffix;
}

fn trimStr(s: &str) -> String {
    return trimStartStr(trimEndStr(s).as_str());
}

fn isWs(c: i64) -> bool {
    if c == 32 {
        return true;
    }
    if c == 9 {
        return true;
    }
    if c == 10 {
        return true;
    }
    if c == 13 {
        return true;
    }
    if c == 11 {
        return true;
    }
    if c == 12 {
        return true;
    }
    return false;
}

fn trimStartStr(s: &str) -> String {
    let mut p: i64 = 0;
    while p < (s.chars().count() as i64) {
        if !(isWs(s.chars().nth((p) as usize).unwrap_or('\0') as i64)) {
            break;
        }
        p += 1;
    }
    if p == 0 {
        return s.to_string();
    }
    return s.chars().skip((p) as usize).collect::<String>().to_string();
}

fn trimEndStr(s: &str) -> String {
    let mut end: i64 = (s.chars().count() as i64);
    while end > 0 {
        if !(isWs(s.chars().nth((end - 1) as usize).unwrap_or('\0') as i64)) {
            break;
        }
        end -= 1;
    }
    if end == (s.chars().count() as i64) {
        return s.to_string();
    }
    return s.chars().take((end) as usize).skip((0) as usize).collect::<String>().to_string();
}

fn findStr(s: &str, needle: &str) -> i64 {
    let nLen: i64 = (needle.chars().count() as i64);
    let sLen: i64 = (s.chars().count() as i64);
    if nLen == 0 {
        return 0;
    }
    if sLen < nLen {
        return -1;
    }
    let mut i: i64 = 0;
    while i + nLen <= sLen {
        if s.chars().take((i + nLen) as usize).skip((i) as usize).collect::<String>() == needle {
            return i;
        }
        i += 1;
    }
    return -1;
}

fn timesInt(n: i64, m: i64) -> i64 {
    let mut r: i64 = 0;
    let mut i: i64 = 0;
    while i < m {
        r += n;
        i += 1;
    }
    return r;
}

fn lowerAlphabet() -> String {
    return "abcdefghijklmnopqrstuvwxyz".to_string();
}

fn asciiLower(s: &str) -> String {
    let mut out: String = "".to_string();
    let lower = lowerAlphabet();
    let mut i: i64 = 0;
    while i < (s.chars().count() as i64) {
        let c = s.chars().nth((i) as usize).unwrap_or('\0') as i64;
        if c >= 65 && c <= 90 {
            out = format!("{}{}", out, lower.chars().take((c - 64) as usize).skip((c - 65) as usize).collect::<String>());
        } else {
            out = format!("{}{}", out, s.chars().take((i + 1) as usize).skip((i) as usize).collect::<String>());
        }

        i += 1;
    }
    return out;
}

fn containsIgnoreCase(hay: &str, needle: &str) -> bool {
    return findStr(asciiLower(hay).as_str(), asciiLower(needle).as_str()) >= 0;
}

fn eqAsciiIgnoreCase(a: &str, b: &str) -> bool {
    if (a.chars().count() as i64) != (b.chars().count() as i64) {
        return false;
    }
    let mut i: i64 = 0;
    while i < (a.chars().count() as i64) {
        let mut ca: i64 = a.chars().nth((i) as usize).unwrap_or('\0') as i64;
        let mut cb: i64 = b.chars().nth((i) as usize).unwrap_or('\0') as i64;
        if ca >= 65 && ca <= 90 {
            ca += 32;
        }
        if cb >= 65 && cb <= 90 {
            cb += 32;
        }
        if ca != cb {
            return false;
        }
        i += 1;
    }
    return true;
}

fn splitWs(s: &str) -> Vec<String> {
    let mut out: Vec<String> = vec![];
    let mut i: i64 = 0;
    let n: i64 = (s.chars().count() as i64);
    while i < n {
        if isWs(s.chars().nth((i) as usize).unwrap_or('\0') as i64) {
            i += 1;
        } else {
            let mut j: i64 = i;
            while j < n {
                if isWs(s.chars().nth((j) as usize).unwrap_or('\0') as i64) {
                    break;
                }
                j += 1;
            }
            out.push(s.chars().take((j) as usize).skip((i) as usize).collect::<String>());
            i = j;
        }

    }
    return out;
}

fn digitsToI64(s: &str) -> i64 {
    if (s.chars().count() as i64) == 0 {
        return -999999999;
    }
    let mut i: i64 = 0;
    let mut neg: i64 = 1;
    if s.chars().nth((0) as usize).unwrap_or('\0') as i64 == 45 {
        neg = -1;
        i = 1;
        if (s.chars().count() as i64) == 1 {
            return -999999999;
        }    }
    let mut v: i64 = 0;
    while i < (s.chars().count() as i64) {
        let c = s.chars().nth((i) as usize).unwrap_or('\0') as i64;
        if c < 48 || c > 57 {
            return -999999999;
        }
        v = timesInt(v, 10) + c - 48;
        i += 1;
    }
    if neg == -1 {
        return 0 - v;
    }
    return v;
}

fn isDigits(s: &str) -> bool {
    if (s.chars().count() as i64) == 0 {
        return false;
    }
    let mut i: i64 = 0;
    while i < (s.chars().count() as i64) {
        let c = s.chars().nth((i) as usize).unwrap_or('\0') as i64;
        if c < 48 || c > 57 {
            return false;
        }
        i += 1;
    }
    return true;
}

fn pad2(n: i64) -> String {
    if n < 10 {
        return format!("{}{}", "0", format!("{:?}", n));
    }
    return format!("{:?}", n);
}

fn intMod(a: i64, m: i64) -> i64 {
    let mut r: i64 = a;
    while r >= m {
        r -= m;
    }
    while r < 0 {
        r += m;
    }
    return r;
}

fn isLeapYear(y: i64) -> bool {
    if intMod(y, 4) != 0 {
        return false;
    }
    if intMod(y, 100) != 0 {
        return true;
    }
    return intMod(y, 400) == 0;
}

fn daysInMonth(y: i64, m: i64) -> i64 {
    if m == 2 {
        if isLeapYear(y) {
            return 29;
        }        return 28;
    }
    if m == 4 || m == 6 || m == 9 || m == 11 {
        return 30;
    }
    return 31;
}

fn addDaysIso(iso: &str, offset: i64) -> String {
    let parts = iso.split("-").map(|s| s.to_string()).collect::<Vec<String>>();
    if (parts.len() as i64) != 3 {
        return iso.to_string();
    }
    let y = digitsToI64(parts[0].as_str());
    let m = digitsToI64(parts[1].as_str());
    let d = digitsToI64(parts[2].as_str());
    if y == -999999999 || m == -999999999 || d == -999999999 {
        return iso.to_string();
    }
    let mut day: i64 = d + offset;
    let mut month: i64 = m;
    let mut year: i64 = y;
    while day > daysInMonth(year, month) {
        day -= daysInMonth(year, month);
        month += 1;
        if month > 12 {
            month = 1;
            year += 1;
        }
    }
    while day < 1 {
        month -= 1;
        if month < 1 {
            month = 12;
            year -= 1;
        }
        day += daysInMonth(year, month);
    }
    let mut ys: String = format!("{:?}", year);
    while (ys.chars().count() as i64) < 4 {
        ys = format!("{}{}", "0", ys);
    }
    return format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", ys, "-"), pad2(month)), "-"), pad2(day));
}

fn taskDateToIso(raw: &str) -> String {
    let mut i: i64 = 0;
    while i < (raw.chars().count() as i64) {
        if isWs(raw.chars().nth((i) as usize).unwrap_or('\0') as i64) {
            break;
        }
        i += 1;
    }
    let token = raw.chars().take((i) as usize).skip((0) as usize).collect::<String>();
    let parts = token.split("-").map(|s| s.to_string()).collect::<Vec<String>>();
    if (parts.len() as i64) != 3 {
        return "".to_string();
    }
    if !(isDigits(parts[1].as_str())) || !(isDigits(parts[2].as_str())) {
        return "".to_string();
    }
    if (parts[1].clone().len() as i64) > 2 || (parts[2].clone().len() as i64) > 2 {
        return "".to_string();
    }
    if !(isDigits(parts[0].as_str())) || (parts[0].clone().len() as i64) != 4 {
        return "".to_string();
    }
    let mo = digitsToI64(parts[1].as_str());
    let da = digitsToI64(parts[2].as_str());
    if mo < 1 || mo > 12 {
        return "".to_string();
    }
    if da < 1 || da > 31 {
        return "".to_string();
    }
    return format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", parts[0].clone(), "-"), pad2(mo)), "-"), pad2(da));
}

fn isoLe(a: &str, b: &str) -> bool {


    let n: i64 = (a.chars().count() as i64);
    if n != (b.chars().count() as i64) {
        return n < (b.chars().count() as i64);
    }
    let mut i: i64 = 0;
    while i < n {
        let ca = a.chars().nth((i) as usize).unwrap_or('\0') as i64;
        let cb = b.chars().nth((i) as usize).unwrap_or('\0') as i64;
        if ca < cb {
            return true;
        }
        if ca > cb {
            return false;
        }
        i += 1;
    }
    return true;
}

fn parseOffsetDays(s: &str) -> OffsetDays {
    let mut t: String = trimStr(s);
    if t == "today" {
        return OffsetDays { ok: true, err: "".to_string(), days: 0 };
    }
    let mut i: i64 = 0;
    let mut digitsEnd: i64 = -1;
    while i < (t.chars().count() as i64) {
        let c = t.chars().nth((i) as usize).unwrap_or('\0') as i64;
        if c >= 48 && c <= 57 || c == 45 {
            digitsEnd = i;
            i += 1;
        } else {
            break;
        }

    }
    if digitsEnd < 0 {
        return OffsetDays { ok: false, err: format!("{}{}", "Invalid offset number: ", s).to_string(), days: 0 };
    }
    let numPart = t.chars().take((i) as usize).skip((0) as usize).collect::<String>();
    let unit = t.chars().skip((i) as usize).collect::<String>();
    if numPart == "" || numPart == "-" {
        return OffsetDays { ok: false, err: format!("{}{}", "Invalid offset number: ", s).to_string(), days: 0 };
    }
    let n = digitsToI64(numPart.as_str());
    if n == -999999999 {
        return OffsetDays { ok: false, err: format!("{}{}", "Invalid offset number: ", s).to_string(), days: 0 };
    }
    if unit == "d" {
        return OffsetDays { ok: true, err: "".to_string(), days: n };
    }
    if unit == "w" {
        return OffsetDays { ok: true, err: "".to_string(), days: timesInt(n, 7) };
    }
    if unit == "m" {
        return OffsetDays { ok: true, err: "".to_string(), days: timesInt(n, 30) };
    }
    if unit == "y" {
        return OffsetDays { ok: true, err: "".to_string(), days: timesInt(n, 365) };
    }
    return OffsetDays { ok: false, err: format!("{}{}", "Invalid offset unit: ", t).to_string(), days: 0 };
}

pub fn evalQuery(input: &str, mut qtask: QueryTask, todayIso: &str) -> QueryEvalOut {
    let mut t: String = trimStr(input);
    if startsWithStr(t.as_str(), dblOpenBrace().as_str()) && endsWithStr(t.as_str(), dblCloseBrace().as_str()) {
        t = trimStr(t.chars().take(((t.chars().count() as i64) - 2) as usize).skip((2) as usize).collect::<String>().as_str());
    }
    if startsWithStr(t.as_str(), "query") {
        t = trimStr(t.chars().skip((5) as usize).collect::<String>().as_str());
    }
    t = trimOuterBraces(t.as_str());
    if t == "" {
        return evalErr("empty query");
    }
    return evalAt(t.as_str(), qtask.clone(), todayIso);
}

fn trimOuterBraces(s: &str) -> String {
    let mut t: String = trimStr(s);
    while startsWithStr(t.as_str(), "(") && endsWithStr(t.as_str(), ")") {
        t = trimStr(t.chars().take(((t.chars().count() as i64) - 1) as usize).skip((1) as usize).collect::<String>().as_str());
    }
    return t;
}

fn evalAt(s: &str, mut qtask: QueryTask, todayIso: &str) -> QueryEvalOut {
    let t = trimOuterBraces(s);
    if t == "" {
        return evalErr("empty query");
    }
    if startsWithStr(t.as_str(), "and ") {
        return evalList(t.chars().skip((4) as usize).collect::<String>().as_str(), qtask.clone(), todayIso, true);
    }
    if startsWithStr(t.as_str(), "or ") {
        return evalList(t.chars().skip((3) as usize).collect::<String>().as_str(), qtask.clone(), todayIso, false);
    }
    if startsWithStr(t.as_str(), "not ") {
        let mut sub = evalAt(t.chars().skip((4) as usize).collect::<String>().as_str(), qtask.clone(), todayIso);
        if sub.ok == false {
            return sub;
        }        return evalOut(notBool(sub.value));
    }
    if startsWithStr(t.as_str(), "task ") {
        let markers = splitWs(t.chars().skip((5) as usize).collect::<String>().as_str());
        let mut hit: bool = false;
        let mut i: i64 = 0;
        while i < (markers.len() as i64) {
            if eqAsciiIgnoreCase(qtask.marker.as_str(), markers[(i) as usize].as_str()) {
                hit = true;
            }
            i += 1;
        }
        return evalOut(hit);
    }
    if startsWithStr(t.as_str(), "priority ") {
        let prios = splitWs(t.chars().skip((9) as usize).collect::<String>().as_str());
        let mut hit: bool = false;
        let mut i: i64 = 0;
        while i < (prios.len() as i64) {
            if qtask.priority != "" && eqAsciiIgnoreCase(qtask.priority.as_str(), prios[(i) as usize].as_str()) {
                hit = true;
            }
            i += 1;
        }
        return evalOut(hit);
    }
    if startsWithStr(t.as_str(), "between ") {
        let parts = splitWs(t.chars().skip((8) as usize).collect::<String>().as_str());
        if (parts.len() as i64) != 2 {
            return evalErr("between expects two offsets");
        }        let startOff = parseOffsetDays(parts[0].as_str());
        if startOff.ok == false {
            return evalErr(startOff.err.as_str());
        }        let endOff = parseOffsetDays(parts[1].as_str());
        if endOff.ok == false {
            return evalErr(endOff.err.as_str());
        }        let startIso = addDaysIso(todayIso, startOff.days);
        let endIso = addDaysIso(todayIso, endOff.days);
        let mut hit: bool = false;
        let d1 = taskDateToIso(qtask.scheduled.as_str());
        if d1 != "" {
            if isoLe(startIso.as_str(), d1.as_str()) && isoLe(d1.as_str(), endIso.as_str()) {
                hit = true;
            }        }        let d2 = taskDateToIso(qtask.deadline.as_str());
        if d2 != "" {
            if isoLe(startIso.as_str(), d2.as_str()) && isoLe(d2.as_str(), endIso.as_str()) {
                hit = true;
            }        }        return evalOut(hit);
    }
    if startsWithStr(t.as_str(), "property ") {
        let body = t.chars().skip((9) as usize).collect::<String>();
        if findStr(body.as_str(), " ") < 0 {
            return evalErr("property expects key and value");
        }        return evalOut(false);
    }
    if startsWithStr(t.as_str(), "[[") && endsWithStr(t.as_str(), "]]") {
        let inner = t.chars().take(((t.chars().count() as i64) - 2) as usize).skip((2) as usize).collect::<String>();
        let hit = eqAsciiIgnoreCase(qtask.title.as_str(), inner.as_str()) || containsIgnoreCase(qtask.content.as_str(), inner.as_str());
        return evalOut(hit);
    }
    if startsWithStr(t.as_str(), "#") {
        let tag = t.chars().skip((1) as usize).collect::<String>();
        let hit = containsIgnoreCase(qtask.content.as_str(), format!("{}{}", "#", tag).as_str()) || findStr(qtask.content.as_str(), format!("{}{}", format!("{}{}", "[[", tag), "]]").as_str()) >= 0;
        return evalOut(hit);
    }
    return evalErr(format!("{}{}", "Unknown query: ", t).as_str());
}

fn evalList(rest: &str, mut qtask: QueryTask, todayIso: &str, isAnd: bool) -> QueryEvalOut {

    let mut anyFalse: bool = false;
    let mut anyTrue: bool = false;
    let n: i64 = (rest.chars().count() as i64);
    let mut depth: i64 = 0;
    let mut start: i64 = 0;
    let mut i: i64 = 0;
    while i <= n {
        let mut boundary: bool = false;
        if i == n {
            boundary = true;
        } else {
            let c = rest.chars().nth((i) as usize).unwrap_or('\0') as i64;
            if c == 40 {
                depth += 1;
            }            if c == 41 {
                depth -= 1;
            }            if c == 32 && depth == 0 {
                boundary = true;
            }        }

        if boundary {
            if i > start {
                let mut sub = evalAt(rest.chars().take((i) as usize).skip((start) as usize).collect::<String>().as_str(), qtask.clone(), todayIso);
                if sub.ok == false {
                    return sub;
                }                if sub.value {
                    anyTrue = true;
                } else {
                    anyFalse = true;
                }
            }            start = i + 1;
        }
        i += 1;
    }
    if isAnd {
        return evalOut(notBool(anyFalse));
    }
    return evalOut(anyTrue);
}
