// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct PropPair {
    pub key: String,
    pub value: String,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct Qa {
    pub question: String,
    pub answer: String,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct SrsBlock {
    pub blockId: String,
    pub uuid: String,
    pub content: String,
    pub lineStart: i64,
    pub lineEnd: i64,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct SrsCardRaw {
    pub pagePath: String,
    pub blockId: String,
    pub uuid: String,
    pub raw: String,
    pub question: String,
    pub answer: String,
    pub deck: String,
    pub easeFactor: String,
    pub repeats: String,
    pub lastInterval: String,
    pub nextSchedule: String,
    pub lastScore: String,
    pub lastReviewed: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SchedOut {
    pub easeFactor: f64,
    pub repeats: i64,
    pub lastInterval: f64,
    pub matrix: Vec<Vec<f64>>,
}

fn startsWithStr(s: &str, prefix: &str) -> bool {
    if (s.chars().count() as i64) < (prefix.chars().count() as i64) {
        return false;
    }
    return s.chars().take(((prefix.chars().count() as i64)) as usize).skip((0) as usize).collect::<String>() == prefix;
}

fn trimStr(s: &str) -> String {
    return trimStartStr(trimEndStr(s).as_str());
}

fn isWs(c: i64) -> bool {
    if c == 32 {
        return true;
    }
    if c == 9 {
        return true;
    }
    if c == 10 {
        return true;
    }
    if c == 13 {
        return true;
    }
    if c == 11 {
        return true;
    }
    if c == 12 {
        return true;
    }
    return false;
}

fn trimStartStr(s: &str) -> String {
    let mut p: i64 = 0;
    while p < (s.chars().count() as i64) {
        if !(isWs(s.chars().nth((p) as usize).unwrap_or('\0') as i64)) {
            break;
        }
        p += 1;
    }
    if p == 0 {
        return s.to_string();
    }
    return s.chars().skip((p) as usize).collect::<String>().to_string();
}

fn trimEndStr(s: &str) -> String {
    let mut end: i64 = (s.chars().count() as i64);
    while end > 0 {
        if !(isWs(s.chars().nth((end - 1) as usize).unwrap_or('\0') as i64)) {
            break;
        }
        end -= 1;
    }
    if end == (s.chars().count() as i64) {
        return s.to_string();
    }
    return s.chars().take((end) as usize).skip((0) as usize).collect::<String>().to_string();
}

fn indentWidth(line: &str) -> i64 {
    let mut p: i64 = 0;
    while p < (line.chars().count() as i64) {
        if !(isWs(line.chars().nth((p) as usize).unwrap_or('\0') as i64)) {
            break;
        }
        p += 1;
    }
    return p;
}

fn isWordChar(c: i64) -> bool {
    if c >= 65 && c <= 90 {
        return true;
    }
    if c >= 97 && c <= 122 {
        return true;
    }
    if c >= 48 && c <= 57 {
        return true;
    }
    if c == 95 {
        return true;
    }
    return false;
}

fn minInt(a: i64, b: i64) -> i64 {
    if a < b {
        return a;
    }
    return b;
}

fn fmax(a: f64, b: f64) -> f64 {
    if a > b {
        return a;
    }
    return b;
}

fn fmin(a: f64, b: f64) -> f64 {
    if a < b {
        return a;
    }
    return b;
}

fn repeatSpaces(n: i64) -> String {
    let mut out: String = "".to_string();
    let mut i: i64 = 0;
    while i < n {
        out = format!("{}{}", out, " ");
        i += 1;
    }
    return out;
}

fn startsWithFrom(s: &str, from: i64, prefix: &str) -> bool {
    if (s.chars().count() as i64) - from < (prefix.chars().count() as i64) {
        return false;
    }
    return s.chars().take((from + (prefix.chars().count() as i64)) as usize).skip((from) as usize).collect::<String>() == prefix;
}

fn hasCardTag(content: &str) -> bool {
    let n: i64 = (content.chars().count() as i64);
    let mut i: i64 = 0;
    while i < n {
        if startsWithFrom(content, i, "#card") {
            if i + 5 >= n {
                return true;
            }            if !(isWordChar(content.chars().nth((i + 5) as usize).unwrap_or('\0') as i64)) {
                return true;
            }        }
        if startsWithFrom(content, i, "[[card]]") {
            return true;
        }
        i += 1;
    }
    return false;
}

fn stripCardTags(s: &str) -> String {
    let n: i64 = (s.chars().count() as i64);
    let mut out: String = "".to_string();
    let mut i: i64 = 0;
    while i < n {
        if startsWithFrom(s, i, "#card") {
            if i + 5 >= n || !(isWordChar(s.chars().nth((i + 5) as usize).unwrap_or('\0') as i64)) {
                i += 5;
            } else {
                out = format!("{}{}", out, s.chars().take((i + 1) as usize).skip((i) as usize).collect::<String>());
                i += 1;
            }
        } else {
            if startsWithFrom(s, i, "[[card]]") {
                i += 8;
            } else {
                out = format!("{}{}", out, s.chars().take((i + 1) as usize).skip((i) as usize).collect::<String>());
                i += 1;
            }
        }

    }
    return trimStr(out.as_str());
}

fn findClozeStart(s: &str, from: i64) -> i64 {
    let n: i64 = (s.chars().count() as i64);
    let mut i: i64 = from;
    while i < n {
        if startsWithFrom(s, i, "{{cloze") {
            return i;
        }
        i += 1;
    }
    return -1;
}

fn findStrFrom(s: &str, needle: &str, from: i64) -> i64 {
    let n: i64 = (s.chars().count() as i64);
    let mut i: i64 = from;
    while i < n {
        if startsWithFrom(s, i, needle) {
            return i;
        }
        i += 1;
    }
    return -1;
}

fn nextCloze(s: &str, from: i64) -> Vec<i64> {

    let mut n: i64 = (s.chars().count() as i64);
    let mut at: i64 = findClozeStart(s, from);
    while at >= 0 {
        let mut i: i64 = at + 7;
        if i >= n {
            return vec![];
        }
        if !(isWs(s.chars().nth((i) as usize).unwrap_or('\0') as i64)) {
            at = findClozeStart(s, at + 1);
        } else {
            while i < n && isWs(s.chars().nth((i) as usize).unwrap_or('\0') as i64) {
                i += 1;
            }
            let mut bs: i64 = i;
            while bs < n {
                if s.chars().nth((bs) as usize).unwrap_or('\0') as i64 == 92 {
                    break;
                }
                bs += 1;
            }
            if bs >= n {
                return vec![];
            }            let mut j: i64 = bs + 1;
            while j < n && isWs(s.chars().nth((j) as usize).unwrap_or('\0') as i64) {
                j += 1;
            }
            let mut close: i64 = findStrFrom(s, "}}", j);
            if close < 0 {
                return vec![];
            }            let mut out: Vec<i64> = vec![];
            out.push(at);
            out.push(close + 2);
            out.push(i);
            out.push(bs);
            out.push(j);
            out.push(close);
            return out;
        }

    }
    return vec![];
}

fn replaceAllStr(s: &str, find: &str, repl: &str) -> String {
    if find == "" {
        return s.to_string();
    }
    let n: i64 = (s.chars().count() as i64);
    let mut out: String = "".to_string();
    let mut i: i64 = 0;
    while i < n {
        if startsWithFrom(s, i, find) {
            out = format!("{}{}", out, repl);
            i += (find.chars().count() as i64);
        } else {
            out = format!("{}{}", out, s.chars().take((i + 1) as usize).skip((i) as usize).collect::<String>());
            i += 1;
        }

    }
    return out;
}

pub fn hasCloze(content: &str) -> bool {
    let hit = nextCloze(content, 0);
    return (hit.len() as i64) > 0;
}

pub fn buildQa(content: &str) -> Qa {
    let mut question: String = content.to_string();
    let mut answer: String = content.to_string();
    let mut from: i64 = 0;
    let mut hit: Vec<i64> = nextCloze(content, from);
    while (hit.len() as i64) > 0 {
        let start = hit[0].clone();
        let end = hit[1].clone();
        let answerText = trimStr(content.chars().take((hit[3].clone()) as usize).skip((hit[2].clone()) as usize).collect::<String>().as_str());
        let hint = trimStr(content.chars().take((hit[5].clone()) as usize).skip((hit[4].clone()) as usize).collect::<String>().as_str());
        let full = content.chars().take((end) as usize).skip((start) as usize).collect::<String>();
        question = replaceAllStr(question.as_str(), full.as_str(), format!("{}{}", format!("{}{}", "{{", hint), "}}").as_str());
        answer = replaceAllStr(answer.as_str(), full.as_str(), format!("{}{}", format!("{}{}", "**", answerText), "**").as_str());
        from = end;
        hit = nextCloze(content, from);
    }
    return Qa { question: stripCardTags(question.as_str()).to_string(), answer: stripCardTags(answer.as_str()).to_string() };
}

pub fn matchPropLine(line: &str) -> PropPair {
    let n: i64 = (line.chars().count() as i64);
    let mut i: i64 = 0;
    while i < n {
        if !(isWs(line.chars().nth((i) as usize).unwrap_or('\0') as i64)) {
            break;
        }
        i += 1;
    }
    let c0 = line.chars().nth((i) as usize).unwrap_or('\0') as i64;
    let mut keyOk: bool = false;
    if c0 >= 65 && c0 <= 90 {
        keyOk = true;
    }
    if c0 >= 97 && c0 <= 122 {
        keyOk = true;
    }
    if c0 == 95 {
        keyOk = true;
    }
    if !(keyOk) {
        return PropPair { key: "".to_string(), value: "".to_string() };
    }
    let mut end: i64 = i + 1;
    while end < n {
        let c = line.chars().nth((end) as usize).unwrap_or('\0') as i64;
        let mut ok: bool = false;
        if c >= 65 && c <= 90 {
            ok = true;
        }
        if c >= 97 && c <= 122 {
            ok = true;
        }
        if c >= 48 && c <= 57 {
            ok = true;
        }
        if c == 95 {
            ok = true;
        }
        if c == 45 {
            ok = true;
        }
        if !(ok) {
            break;
        }
        end += 1;
    }
    if !(startsWithFrom(line, end, "::")) {
        return PropPair { key: "".to_string(), value: "".to_string() };
    }
    let mut v: i64 = end + 2;
    while v < n {
        if !(isWs(line.chars().nth((v) as usize).unwrap_or('\0') as i64)) {
            break;
        }
        v += 1;
    }
    return PropPair { key: line.chars().take((end) as usize).skip((i) as usize).collect::<String>().to_string(), value: trimStr(line.chars().skip((v) as usize).collect::<String>().as_str()).to_string() };
}

pub fn parseBlockProps(mut lines: Vec<String>, lineStart: i64, lineEnd: i64) -> Vec<PropPair> {
    let mut out: Vec<PropPair> = vec![];
    let count: i64 = (lines.len() as i64);
    let mut hardEnd: i64 = lineEnd;
    if hardEnd > count {
        hardEnd = count;
    }
    let mut i: i64 = lineStart;
    while i < hardEnd {
        let p = matchPropLine(lines[(i) as usize].as_str());
        if p.key != "" {
            let mut replaced: bool = false;
            let mut q: i64 = 0;
            while q < (out.len() as i64) {
                if out[(q) as usize].clone().key == p.key {
                    out[(q) as usize] = PropPair { key: p.key.to_string(), value: p.value.to_string() };
                    replaced = true;
                }
                q += 1;
            }
            if !(replaced) {
                out.push(p.clone());
            }        }
        i += 1;
    }

    if lineStart < count {
        let blockIndent = indentWidth(lines[(lineStart) as usize].as_str());
        let mut j: i64 = lineEnd;
        if j < lineStart + 1 {
            j = lineStart + 1;
        }        while j < count {
            let line = lines[(j) as usize].clone();
            if trimStr(line.as_str()) == "" {
                break;
            }
            if indentWidth(line.as_str()) <= blockIndent {
                break;
            }
            let p = matchPropLine(line.as_str());
            if p.key != "" {
                let mut replaced: bool = false;
                let mut q: i64 = 0;
                while q < (out.len() as i64) {
                    if out[(q) as usize].clone().key == p.key {
                        out[(q) as usize] = PropPair { key: p.key.to_string(), value: p.value.to_string() };
                        replaced = true;
                    }
                    q += 1;
                }
                if !(replaced) {
                    out.push(p.clone());
                }            }
            j += 1;
        }
    }
    return out;
}

fn propAt(mut props: Vec<PropPair>, key: &str) -> String {
    let mut val: String = "".to_string();
    let mut q: i64 = 0;
    while q < (props.len() as i64) {
        if props[(q) as usize].clone().key == key {
            val = props[(q) as usize].clone().value;
        }
        q += 1;
    }
    return val;
}

pub fn extractCards(pagePath: &str, mut lines: Vec<String>, mut blocks: Vec<SrsBlock>) -> Vec<SrsCardRaw> {
    let mut out: Vec<SrsCardRaw> = vec![];
    let count: i64 = (blocks.len() as i64);
    let mut i: i64 = 0;
    while i < count {
        let mut b = blocks[(i) as usize].clone();
        if b.blockId == "" {
            i += 1;
        } else {
            if hasCardTag(b.content.as_str()) || hasCloze(b.content.as_str()) {
                let qa = buildQa(b.content.as_str());
                let props = parseBlockProps(lines.clone(), b.lineStart, b.lineEnd);
                out.push(SrsCardRaw { pagePath: pagePath.to_string(), blockId: b.blockId.to_string(), uuid: b.uuid.to_string(), raw: b.content.to_string(), question: qa.question.to_string(), answer: qa.answer.to_string(), deck: propAt(props.clone(), "deck").to_string(), easeFactor: propAt(props.clone(), "card-ease-factor").to_string(), repeats: propAt(props.clone(), "card-repeats").to_string(), lastInterval: propAt(props.clone(), "card-last-interval").to_string(), nextSchedule: propAt(props.clone(), "card-next-schedule").to_string(), lastScore: propAt(props.clone(), "card-last-score").to_string(), lastReviewed: propAt(props.clone(), "card-last-reviewed").to_string() });
            }            i += 1;
        }

    }
    return out;
}

pub fn matrixFactor(mut matrix: Vec<Vec<f64>>, repetition: i64, grade: i64) -> f64 {
    if (matrix.len() as i64) == 0 {
        return 2.5;
    }
    let r = minInt(repetition, 4);
    if r < 0 {
        return 2.5;
    }
    if r >= (matrix.len() as i64) {
        return 2.5;
    }
    let row = matrix[(r) as usize].clone();
    let mut g: i64 = 0;
    if grade > 1 {
        g = minInt(grade - 1, 4);
    }
    if g >= (row.len() as i64) {
        return 2.5;
    }
    return row[(g) as usize].clone();
}

fn fiveRow() -> Vec<f64> {
    let mut row: Vec<f64> = vec![];
    row.push(2.5);
    row.push(2.5);
    row.push(2.5);
    row.push(2.5);
    row.push(2.5);
    return row;
}

fn copyFloatRow(mut row: Vec<f64>) -> Vec<f64> {
    let mut out: Vec<f64> = vec![];
    let mut i: i64 = 0;
    while i < (row.len() as i64) {
        out.push(row[(i) as usize].clone());
        i += 1;
    }
    return out;
}

pub fn matrixUpdate(mut matrix: Vec<Vec<f64>>, repetition: i64, grade: i64, requested: f64) -> Vec<Vec<f64>> {
    let r = minInt(repetition, 4);
    let mut g: i64 = 0;
    if grade > 1 {
        g = minInt(grade - 1, 4);
    }
    let mut out: Vec<Vec<f64>> = vec![];



    let mut total: i64 = (matrix.len() as i64);
    if total == 0 {
        total = 5;
    }
    if total <= r {
        total = r + 1;
    }
    let mut idx: i64 = 0;
    while idx < total {
        let mut row: Vec<f64> = vec![];
        if (matrix.len() as i64) == 0 {
            row = fiveRow();
        } else {
            if idx < (matrix.len() as i64) {
                row = copyFloatRow(matrix[(idx) as usize].clone());
            } else {
                row = fiveRow();
            }
        }

        if idx == r {
            while (row.len() as i64) <= g {
                row.push(2.5);
            }
            let current = row[(g) as usize].clone();
            let mut modifier: f64 = 0.0;
            if grade == 1 {
                modifier = -0.3;
            }            if grade == 2 {
                modifier = -0.15;
            }            if grade == 3 {
                modifier = 0.0;
            }            if grade == 4 {
                modifier = 0.1;
            }            


            let diff: f64 = requested - current;
            let delta: f64 = diff * 0.1;
            let change: f64 = delta + modifier;
            let bumped: f64 = current + change;
            let lo = fmax(bumped, 1.3);
            row[(g) as usize] = fmin(lo, 3.0);
        }
        out.push(row);
        idx += 1;
    }
    return out;
}

pub fn scheduleWith(easeFactor: f64, repeats: i64, lastInterval: f64, grade: i64, mut matrix: Vec<Vec<f64>>) -> SchedOut {
    let mut g: i64 = grade;
    if g < 1 {
        g = 1;
    }
    if g > 4 {
        g = 4;
    }
    let mut reps: i64 = repeats;
    let mut interval: f64 = lastInterval;
    let mut ef: f64 = easeFactor;
    if g == 1 {
        reps = 0;
        interval = 0.0;
    } else {
        reps = reps + 1;
        if reps == 1 {
            interval = 1.0;
        } else {
            if reps == 2 {
                interval = 6.0;
            } else {
                let factor = matrixFactor(matrix.clone(), minInt(reps, 4), g);
                let prod: f64 = interval * factor;
                interval = fmax(prod, ef);
            }
        }
    }

    let q: f64 = 5.0 - (g as f64);
    let inner: f64 = 0.08 + q * 0.02;
    let adjust: f64 = 0.1 - q * inner;
    let bumped: f64 = ef + adjust;
    ef = fmax(bumped, 1.3);
    let nextMatrix = matrixUpdate(matrix.clone(), minInt(reps, 4), g, interval);
    return SchedOut { easeFactor: ef, repeats: reps, lastInterval: interval, matrix: nextMatrix };
}

pub fn findAnchorLine(mut lines: Vec<String>, anchor: &str) -> i64 {
    let count: i64 = (lines.len() as i64);
    let mut i: i64 = 0;
    while i < count {
        let line = lines[(i) as usize].clone();
        let trimmed = trimEndStr(line.as_str());
        if (trimmed.chars().count() as i64) >= (anchor.chars().count() as i64) {
            let tail: i64 = (trimmed.chars().count() as i64) - (anchor.chars().count() as i64);
            if trimmed.chars().skip((tail) as usize).collect::<String>() == anchor {
                return i;
            }        }
        i += 1;
    }
    return -1;
}

pub fn applyReviewProps(mut lines: Vec<String>, blockLine: i64, mut newProps: Vec<PropPair>) -> Vec<String> {
    let count: i64 = (lines.len() as i64);
    let blockIndent = indentWidth(lines[(blockLine) as usize].as_str());
    let mut endLine: i64 = count;
    let mut i: i64 = blockLine + 1;
    while i < count {
        let line = lines[(i) as usize].clone();
        if trimStr(line.as_str()) == "" {
            endLine = i;
        }
        if indentWidth(line.as_str()) <= blockIndent {
            endLine = i;
        }
        if endLine != count {
            break;
        }
        i += 1;
    }



    let mut picked: Vec<String> = vec![];
    let mut used: Vec<i64> = vec![];
    let indent = repeatSpaces(blockIndent + 2);
    while (used.len() as i64) < (newProps.len() as i64) {
        let mut best: String = "".to_string();
        let mut bestIdx: i64 = -1;
        let mut j: i64 = 0;
        while j < (newProps.len() as i64) {
            let mut alreadyUsed: bool = false;
            let mut u: i64 = 0;
            while u < (used.len() as i64) {
                if used[(u) as usize].clone() == j {
                    alreadyUsed = true;
                }
                u += 1;
            }
            if !(alreadyUsed) {
                let cand: String = format!("{}{}", format!("{}{}", format!("{}{}", indent, newProps[(j) as usize].clone().key), ":: "), newProps[(j) as usize].clone().value);
                if bestIdx < 0 || cand < best {
                    best = cand.to_string();
                    bestIdx = j;
                }            }
            j += 1;
        }
        used.push(bestIdx);
        picked.push(best.to_string());
    }

    let mut out: Vec<String> = vec![];
    let mut k: i64 = 0;
    while k < count {
        if k == blockLine {
            out.push(lines[(k) as usize].clone());
            let mut p: i64 = 0;
            while p < (picked.len() as i64) {
                out.push(picked[(p) as usize].clone());
                p += 1;
            }
        } else {
            let mut drop: bool = false;
            if k > blockLine && k < endLine {
                let pr = matchPropLine(lines[(k) as usize].as_str());
                if pr.key != "" {
                    let mut q: i64 = 0;
                    while q < (newProps.len() as i64) {
                        if newProps[(q) as usize].clone().key == pr.key {
                            drop = true;
                        }
                        q += 1;
                    }
                }            }            if !(drop) {
                out.push(lines[(k) as usize].clone());
            }        }

        k += 1;
    }
    return out;
}
