// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct TaskScanItem {
    pub pagePath: String,
    pub title: String,
    pub line: i64,
    pub raw: String,
    pub marker: String,
    pub priority: String,
    pub content: String,
    pub scheduled: String,
    pub deadline: String,
}

fn startsWithStr(s: &str, prefix: &str) -> bool {
    if (s.chars().count() as i64) < (prefix.chars().count() as i64) {
        return false;
    }
    return s.chars().take(((prefix.chars().count() as i64)) as usize).skip((0) as usize).collect::<String>() == prefix;
}

pub fn trimStr(s: &str) -> String {
    return trimStartStr(trimEndStr(s).as_str());
}

fn isWs(c: i64) -> bool {
    if c == 32 {
        return true;
    }
    if c == 9 {
        return true;
    }
    if c == 10 {
        return true;
    }
    if c == 13 {
        return true;
    }
    if c == 11 {
        return true;
    }
    if c == 12 {
        return true;
    }
    return false;
}

fn trimStartStr(s: &str) -> String {
    let mut p: i64 = 0;
    while p < (s.chars().count() as i64) {
        if !(isWs(s.chars().nth((p) as usize).unwrap_or('\0') as i64)) {
            break;
        }
        p += 1;
    }
    if p == 0 {
        return s.to_string();
    }
    return s.chars().skip((p) as usize).collect::<String>().to_string();
}

fn trimEndStr(s: &str) -> String {
    let mut end: i64 = (s.chars().count() as i64);
    while end > 0 {
        if !(isWs(s.chars().nth((end - 1) as usize).unwrap_or('\0') as i64)) {
            break;
        }
        end -= 1;
    }
    if end == (s.chars().count() as i64) {
        return s.to_string();
    }
    return s.chars().take((end) as usize).skip((0) as usize).collect::<String>().to_string();
}

fn indentWidth(line: &str) -> i64 {
    let mut p: i64 = 0;
    while p < (line.chars().count() as i64) {
        if !(isWs(line.chars().nth((p) as usize).unwrap_or('\0') as i64)) {
            break;
        }
        p += 1;
    }
    return p;
}

fn isWordChar(c: i64) -> bool {
    if c >= 65 && c <= 90 {
        return true;
    }
    if c >= 97 && c <= 122 {
        return true;
    }
    if c >= 48 && c <= 57 {
        return true;
    }
    if c == 95 {
        return true;
    }
    return false;
}

fn isMarkerKwAt(s: &str) -> String {
    if startsWithStr(s, "TODO") {
        return markerIfBoundary(s, 4);
    }
    if startsWithStr(s, "DOING") {
        return markerIfBoundary(s, 5);
    }
    if startsWithStr(s, "DONE") {
        return markerIfBoundary(s, 4);
    }
    if startsWithStr(s, "NOW") {
        return markerIfBoundary(s, 3);
    }
    if startsWithStr(s, "LATER") {
        return markerIfBoundary(s, 5);
    }
    return "".to_string();
}

fn markerIfBoundary(s: &str, kwLen: i64) -> String {
    let next = s.chars().nth((kwLen) as usize).unwrap_or('\0') as i64;
    if isWordChar(next) {
        return "".to_string();
    }
    return s.chars().take((kwLen) as usize).skip((0) as usize).collect::<String>().to_string();
}

fn taskMarkerOf(line: &str) -> String {
    let indent = indentWidth(line);
    let rest = line.chars().skip((indent) as usize).collect::<String>();
    if !(startsWithStr(rest.as_str(), "- ")) {
        return "".to_string();
    }
    return isMarkerKwAt(rest.chars().skip((2) as usize).collect::<String>().as_str());
}

fn isPriorityTagAt(s: &str, at: i64) -> bool {

    if !(startsWithStr(s.chars().skip((at) as usize).collect::<String>().as_str(), "[#")) {
        return false;
    }
    let c = s.chars().nth((at + 2) as usize).unwrap_or('\0') as i64;
    if c != 65 && c != 66 && c != 67 {
        return false;
    }
    return s.chars().nth((at + 3) as usize).unwrap_or('\0') as i64 == 93;
}

fn findPriorityTag(rest: &str) -> String {
    let n: i64 = (rest.chars().count() as i64);
    let mut i: i64 = 0;
    while i + 3 < n {
        if isPriorityTagAt(rest, i) {
            return rest.chars().take((i + 3) as usize).skip((i + 2) as usize).collect::<String>().to_string();
        }
        i += 1;
    }
    return "".to_string();
}

fn stripPriorityTag(content: &str) -> String {


    let n: i64 = (content.chars().count() as i64);
    let mut found: i64 = -1;
    let mut i: i64 = 0;
    while i + 3 < n {
        if isPriorityTagAt(content, i) {
            found = i;
            break;
        }
        i += 1;
    }
    if found < 0 {
        return trimStr(content);
    }
    let mut out: String = "".to_string();
    let mut k: i64 = 0;
    while k < n {
        if k == found || k == found + 1 || k == found + 2 || k == found + 3 {
            

        } else {
            out = format!("{}{}", out, content.chars().take((k + 1) as usize).skip((k) as usize).collect::<String>());
        }

        k += 1;
    }
    return trimStr(out.as_str());
}

fn scheduleValueOf(line: &str) -> String {
    let p = indentWidth(line);
    let rest = line.chars().skip((p) as usize).collect::<String>();
    let mut kwLen: i64 = 0;
    if startsWithStr(rest.as_str(), "SCHEDULED:") {
        kwLen = 10;
    } else {
        if startsWithStr(rest.as_str(), "DEADLINE:") {
            kwLen = 9;
        } else {
            return "".to_string();
        }
    }

    let v = trimStartStr(rest.chars().skip((kwLen) as usize).collect::<String>().as_str());
    if v.chars().nth((0) as usize).unwrap_or('\0') as i64 != 60 {
        return "".to_string();
    }
    let mut j: i64 = 1;
    while j < (v.chars().count() as i64) {
        if v.chars().nth((j) as usize).unwrap_or('\0') as i64 == 62 {
            return v.chars().take((j) as usize).skip((1) as usize).collect::<String>().to_string();
        }
        j += 1;
    }
    return "".to_string();
}

pub fn parseTasksLines(pagePath: &str, title: &str, mut lines: Vec<String>) -> Vec<TaskScanItem> {
    let mut out: Vec<TaskScanItem> = vec![];
    let count: i64 = (lines.len() as i64);
    let mut i: i64 = 0;
    while i < count {
        let line = lines[(i) as usize].clone();
        let marker = taskMarkerOf(line.as_str());
        if marker != "" {
            let indent = indentWidth(line.as_str());
            let rest = line.chars().skip((indent + 2 + (marker.chars().count() as i64)) as usize).collect::<String>();
            let priority = findPriorityTag(rest.as_str());
            let content = stripPriorityTag(trimStr(rest.as_str()).as_str());
            

            let mut scheduled: String = "".to_string();
            let mut deadline: String = "".to_string();
            let mut j: i64 = i + 1;
            while j < count {
                let next = lines[(j) as usize].clone();
                let nextIndent = indentWidth(next.as_str());
                if trimStr(next.as_str()) == "" || nextIndent <= indent {
                    break;
                }
                let sv = scheduleValueOf(next.as_str());
                if sv != "" {
                    if startsWithStr(trimStartStr(next.as_str()).as_str(), "SCHEDULED:") {
                        scheduled = sv.to_string();
                    } else {
                        deadline = sv.to_string();
                    }
                }
                j += 1;
            }
            out.push(TaskScanItem { pagePath: pagePath.to_string(), title: title.to_string(), line: i, raw: line.to_string(), marker: marker.to_string(), priority: priority.to_string(), content: content.to_string(), scheduled: scheduled.to_string(), deadline: deadline.to_string() });
        }
        i += 1;
    }
    return out;
}
